### ISSUE TITLE
Problem since update version

### ISSUE THREAD

**Issue by saianwork** [TA-Lib/ta-lib-python#180]
Hi,
i get this error in a code that was working previsously 
example:

`import talib`
`ema12 = talib.EMA(close, timeperiod=12)`

`File "talib/func.pyx", line 7092, in talib.func.EMA (talib\func.c:79408)`

your documentation doesn't work for me i've read already a lot of things no one seems to have the issue. I have it on mac and pc same code that was working before on both

thanks guys

**Comment by mrjbq7** [comment]
``func.pyx`` doesn't exist and hasn't since ddce83fdb72bb0bc1b1311cc73d524d8bdb59556.

Perhaps you didn't fully update to the latest version?

**Comment by mrjbq7** [comment]
Can you show me what ``talib.__version__`` is?

**Comment by mrjbq7** [comment]
Also, what is the type of close?

**Comment by saianwork** [comment]
I feel something is missing yes. when I do any 
`talib.ema or talib.sma`

it says: couldn't find reference EMA in init.py

if I do `ema12 = talib.abstract.Function('EMA',close,timeperiod=12)`  this works
but it wasn't like that. I have the same issue on mac and pc 
problem is I'm working on PC now and I'm sure I have the version  0.4.16 but had to install with wheel because x64 windows. but on mac I didn't touch anything even tried to update now and have the same issue

**Comment by saianwork** [comment]
close is numpy array works fine when i like this 
`ema12 = talib.abstract.Function('EMA',close,timeperiod=12)`

**Comment by saianwork** [comment]
I work with pycharm btw

**Comment by saianwork** [comment]
version : 0.4.16

**Comment by saianwork** [comment]
something is weird here are you sure you deployed right version on git?

**Comment by mrjbq7** [comment]
The ``TA-Lib-0.4.16.tar.gz`` does not contain a ``_func.pyx``:

```
TA-Lib-0.4.16
TA-Lib-0.4.16/talib
TA-Lib-0.4.16/talib/abstract.py
TA-Lib-0.4.16/talib/_ta_lib.pyx
TA-Lib-0.4.16/talib/test_abstract.py
TA-Lib-0.4.16/talib/deprecated.py
TA-Lib-0.4.16/talib/__init__.py
TA-Lib-0.4.16/talib/stream.py
TA-Lib-0.4.16/talib/test_data.py
TA-Lib-0.4.16/talib/test_func.py
TA-Lib-0.4.16/talib/_ta_lib.c
TA-Lib-0.4.16/talib/test_stream.py
TA-Lib-0.4.16/PKG-INFO
TA-Lib-0.4.16/LICENSE
TA-Lib-0.4.16/TA_Lib.egg-info
TA-Lib-0.4.16/TA_Lib.egg-info/PKG-INFO
TA-Lib-0.4.16/TA_Lib.egg-info/SOURCES.txt
TA-Lib-0.4.16/TA_Lib.egg-info/requires.txt
TA-Lib-0.4.16/TA_Lib.egg-info/top_level.txt
TA-Lib-0.4.16/TA_Lib.egg-info/dependency_links.txt
TA-Lib-0.4.16/MANIFEST.in
TA-Lib-0.4.16/README
TA-Lib-0.4.16/README.md
TA-Lib-0.4.16/setup.py
TA-Lib-0.4.16/setup.cfg
TA-Lib-0.4.16/COPYRIGHT
```

**Comment by mrjbq7** [comment]
Did you upgrade with ``pip install --upgrade ta-lib``?

**Comment by saianwork** [comment]
no i installed from here https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib

with this command pip install TA_Lib-0.4.16-cp36-cp36m-win32.whl otherwise it's close to impossible to run it on winx64 

but on my mac I upgraded normally and still have the same issue

**Comment by saianwork** [comment]
Can you provide a ready to install Ta-lib for win x64 please? the compilation with make run never works properly

**Comment by mrjbq7** [comment]
I am not the maintainer of the underlying C library, so do not provide binaries for it.

You can follow these instructions to create a 64-bit build for Windows:

https://github.com/mrjbq7/ta-lib/issues/127#issuecomment-280222942

I probably should get a build environment that lets me produce "official" wheels instead of relying on gohlke.  I haven't tested his version, although I would note that the one you pasted is "win32" not "win64".

**Comment by saianwork** [comment]
yes If i use win64 version to install it it won't work because my python is 32bit maybe i shouls get x64 version i'll see. but any way as I told you on mac I have the same issue and the installation comes from official source... how come?

**Comment by mrjbq7** [comment]
No idea. 

Maybe delete all the ta-lib artifacts from the python site-packages (pip uninstall, or manually) and try reinstalling. 

Something seems screwy with your installation that I have not seen before. It’s like you have two versions installed at the same time.

**Comment by mrjbq7** [comment]
Closing old issue.
