### ISSUE TITLE
Missing documentation?

### ISSUE THREAD

**Issue by blackice999** [TA-Lib/ta-lib-python#184]
Hello,

Finally I managed to install this library but the problem is that the documentation's most important parts are missing, specifically the part about all the indicators and it's properties. Where can I find the usage of these indicators?

**Comment by mrjbq7** [comment]
What specifically are you missing?

**Comment by blackice999** [comment]
I see that the docs/func_groups directory contains the indicators, but it does not specify a return value for them, or anything close to be a valid function description.

**Comment by mrjbq7** [comment]
Each function has basic docstrings:

```python
>>> import talib
>>> help(talib.MOM)
Help on function MOM in module talib._ta_lib:

MOM(...)
    MOM(real[, timeperiod=?])
    
    Momentum (Momentum Indicators)
    
    Inputs:
        real: (any ndarray)
    Parameters:
        timeperiod: 10
    Outputs:
        real
```

If you're looking for further documentation on each indicator, you can look at http://tadoc.org/ or the underlying TA-LIb source code:

https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/

**Comment by blackice999** [comment]
I see. Thank you, however it should be useful to include this also in the docs :)

**Comment by mrjbq7** [comment]
I mean basically those are in the docs already, but in a compressed form:

### MOM - Momentum
```python
real = MOM(close, timeperiod=10)
```

Learn more about the Momentum at [tadoc.org](http://www.tadoc.org/indicator/MOM.htm).

**Comment by mrjbq7** [comment]
(We could always use better docs, but I have so far chosen to just link to the underlying TA-Lib C library documentation rather than write my own. Maybe it's worth improving it...)

**Comment by blackice999** [comment]
Of course, it would be easier to use this wrapper this way, I think. Anyways, thank you for the quick reply and I wish you a pleasant afternoon

**Comment by FingerDrill** [comment]
@mrjbq7 Can you give me more information on MACDEXT? Specifically about fastmatype, slowmatype, and signalmatype, I don't know which value represents which moving average type.

**Comment by mrjbq7** [comment]
Short answer:

The "moving average types" are integers, mapping to the ``TA_MAType`` enum in the underlying C library:

```
SMA    0    Simple Moving Average
EMA    1    Exponential Moving Average
WMA    2    Weighted Moving Average
DEMA   3    Double Exponential Moving Average
TEMA   4    Triple Exponential Moving Average
TRIMA  5    Triangular Moving Average
KAMA   6    Kaufman Adaptive Moving Average
MAMA   7    MESA Adaptive Moving Average
T3     8    Triple Generalized Double Exponential Moving Average
```

Long answer:

We've tried a few different approaches, including these constants that were deprecated:

```python
# TA_MAType enums
MA_SMA, MA_EMA, MA_WMA, MA_DEMA, MA_TEMA, MA_TRIMA, MA_KAMA, MA_MAMA, MA_T3 = range(9)
```

Replaced by a class approach:

```python
class MA_Type(object):
     SMA, EMA, WMA, DEMA, TEMA, TRIMA, KAMA, MAMA, T3 = range(9)
```

And then that got deleted as part of some cleanup, and we're stuck using integers again.

Thanks for reminding me, I forgot to come back and try and clean this up and document it.

Do you have any thoughts about approach here?

**Comment by FingerDrill** [comment]
@mrjbq7 Thanks for fast replying. I think integer or constant seems to be enough.

**Comment by mrjbq7** [comment]
Closing old issue.
