### ISSUE TITLE
aarch64 arm

### ISSUE THREAD

**Issue by fachos** [TA-Lib/ta-lib-python#222]
hi... i got error while ./configure... config.sub & config.guess im running os pi64 

uname -m = aarch64
uname -r = 4.11.12-pi64+
uname -s = Linux
uname -v = #1 SMP PREEMPT Sun Aug 27 14:50:58 CEST 2017

/usr/bin/uname -p =
/bin/uname -X     =

hostinfo               =
/bin/universe          =
/usr/bin/arch -k       =
/bin/arch              =
/usr/bin/oslevel       =
/usr/convex/getsysinfo =

UNAME_MACHINE = aarch64
UNAME_RELEASE = 4.11.12-pi64+
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP PREEMPT Sun Aug 27 14:50:58 CEST 2017
configure: error: cannot guess build type; you must specify one

**Comment by mrjbq7** [comment]
We don’t currently have ARM support in the compiler.  There was some work on it recently, but I think not finished.

**Comment by mrjbq7** [comment]
Hah, oh sorry. I thought this was one of my other projects. I’m actually not sure or ARM support of underlying TA-Lib C library.

**Comment by fachos** [comment]
hi again... i solve the problem... due the config.sub & config.guess too old.... for future use need to replace these files inside directory of Ta-Lib... then all good to go ./configure

`wget 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD' -O config.guess` 

`wget 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' -O config.sub`

**Comment by mario4tier** [comment]
This is now likely fix in release 0.6.1

Whenever there is a Makefile problem, consider trying an "autoreconf -fi" on a checkout of TA-Lib.
