### ISSUE TITLE
 conda install -c jiayi_anaconda ta-lib 

### ISSUE THREAD

**Issue by zhu4ling3** [TA-Lib/ta-lib-python#253]
hello,

i have just installed TA-Lib with the following command on Linux x64:
 conda install -c jiayi_anaconda ta-lib 

when i executed "import talib", it was said the libta_lib.so.0 no found.
i thought the ta-lib C library is missing, so i got it from quantopian package(https://anaconda.org/Quantopian/ta-lib/0.4.9/download/linux-64/ta-lib-0.4.9-np114py35_0.tar.bz2), and put it into local directory, finally the problem was solved.

i think if your conda package can include the ta-lib C library itself, it will be better.

**Comment by mrjbq7** [comment]
Closing old issue.
