### ISSUE TITLE
SSMA - smoothed simple moving average

### ISSUE THREAD

**Issue by rrfaria** [TA-Lib/ta-lib-python#259]
Hello, first of all thank you for your amazing job.

I would like to ask you if do you know how to calculate ssma?

I saw this indicator on iqoption site but I can't found how to calc this.

I found SMA but not SSMA.

could you help me ?

**Comment by mrjbq7** [comment]
If you have a link to any literature, I could help look it up.  But likely these two links describe the same indicator:

https://apiaryfund.com/training/glossary/ssma-smooth-simple-moving-average

https://mahifx.com/mfxtrade/indicators/smoothed-moving-average-smma

The indicated calculation seems pretty simple to implement. Let me know if you want help with getting something to work.

**Comment by rrfaria** [comment]
fallowing first link I did this js

```js
// (sum of the close prices of the candles in the period)-(SMA of the candles in the period)+(current price)Period

const ssma = (closes = [], sma, currentPrice, period) => {
	const closesSum = closes.reduce( (accum, curr) => accum + curr );
	const calc = (closesSum - sma + currentPrice) * period;
	return calc;
}
```

**Comment by skiplai** [comment]
@rrfaria  Smoothed Moving Average =SMMA
you can find answer from this page
https://www.ricequant.com/community/topic/3749/%E5%9F%BA%E7%9F%B3%E6%95%99%E7%A8%8B-ema-%E4%B8%8E-smma-%E7%9A%84%E5%AE%9E%E7%8E%B0

**Comment by skiplai** [comment]
@rrfaria  I think you want this?

    def smma(self,prices,period):
        sum=0
        last=0
        for i,price in enumerate(prices):
            if(i<period-1):
                sum+=price
                yield 0.0
                continue
            elif(i==period-1):
                sum+=price
                last=sum/period
                yield last
                continue
            else:
                last=(last*(period-1)+price)/period
                yield last

**Comment by mario4tier** [comment]
This is now implemented as TA_RMA in the next planned release of TA-Lib Core v0.8.1
https://github.com/TA-Lib/ta-lib/issues/348
