### ISSUE TITLE
I can't get  ta-lib functions default arguments

### ISSUE THREAD

**Issue by JourneyToSilius** [TA-Lib/ta-lib-python#274]
I need to get function default arguments for ta-lib but  when I do : 

```
import talib.abstract as ta
import inspect
cat = dir(ta)

def getRequiredArgs(func):
    sig = inspect.signature(func).parameters
    print(sig)

for x in cat:
    if x == 'BBANDS':
        call_ta = getattr(ta, x)
        this  = getRequiredArgs(call_ta)
```

I get this : `OrderedDict([('args', <Parameter "*args">), ('kwargs', <Parameter "**kwargs">)])`

Normally I can get all the args from a function like this, is this because ta-lib is a wrapper? Is there a way to call directly the Cython functions somehow to get the actual arguments that you supply to the function? Also, if this is not possible but there is another way to do it, I'll be glad to know !

**Comment by mrjbq7** [comment]
You can get that from the Abstract API:

```python
>>> import talib.abstract as ta

>>> ta.BBANDS.input_names                                                                                         
OrderedDict([('price', 'close')])

>>> ta.BBANDS.parameters                                                                                          
OrderedDict([('timeperiod', 5), ('nbdevup', 2), ('nbdevdn', 2), ('matype', 0)])

>>> ta.BBANDS.output_names                                                                                        
['upperband', 'middleband', 'lowerband']

>>> ta.BBANDS.info
{'name': 'BBANDS',
 'group': 'Overlap Studies',
 'display_name': 'Bollinger Bands',
 'function_flags': ['Output scale same as input'],
 'input_names': OrderedDict([('price', 'close')]),
 'parameters': OrderedDict([('timeperiod', 5),
              ('nbdevup', 2),
              ('nbdevdn', 2),
              ('matype', 0)]),
 'output_flags': OrderedDict([('upperband',
               ['Values represent an upper limit']),
              ('middleband', ['Line']),
              ('lowerband', ['Values represent a lower limit'])]),
 'output_names': ['upperband', 'middleband', 'lowerband']}
```

That corresponds to *args, **kwargs, and return values.

You can see by looking at ``ta.ADXR``, an example where it takes several price arrays as arguments (high, low, close), instead of a single price.  It's a little awkward right now, for example ``ta.OBV``, probably should look a little different, but it was designed like that to allow any price. array to be specified, but then use the volume column as volume...

**Comment by mrjbq7** [comment]
It looks like ``cython`` has an attribute ``binding`` that can be used to fix support for signatures (e.g., ``inspect.signature(ta._ta_lib.BBANDS)``):

https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives

> ``binding`` (True / False)
>    Controls whether free functions behave more like Python’s CFunctions (e.g. len()) or, when set to True, more like Python’s functions. When enabled, functions will bind to an instance when looked up as a class attribute (hence the name) and will emulate the attributes of Python functions, including introspections like argument names and annotations. Default is False.

You could try adding this to the top of your ``_func.pxi`` and then re-building the TA-Lib python wrapper:

```# cython: binding=True```

**Comment by chromafunk** [comment]
that's helpful, thanks !

**Comment by mrjbq7** [comment]
Closing old issue.
