### ISSUE TITLE
Feature Question - Renko

### ISSUE THREAD

**Issue by Corfucinas** [TA-Lib/ta-lib-python#362]
Hi, 

Is there's currently any interest in adding Renko for Candlesticks? I tried to see if anyone commented about this in an issue or a PR, but seems no.

**Comment by mrjbq7** [comment]
That is better contributed upstream. This is just a lightweight wrapper for the TA-Lib C library!

**Comment by mario4tier** [comment]
Moving forward, all requests and further discussion for **new** functions should happen on the [New TA Functions Board]( https://github.com/orgs/TA-Lib/projects/1 )

A reference to this issue has been added to preserve this discussion. Thanks!
