### ISSUE TITLE
Deploy to conda-forge

### ISSUE THREAD

**Issue by tylerwmarrs** [TA-Lib/ta-lib-python#389]
I'm not sure if you are willing to pay for TravisCI, but it will cost you about $69 USD per month once your 10K free credits are used. Additionally, OSX builds require you to buy credits at $15 USD per pool of credits. The pool of OSx credits can be burned through rather quickly, depending on your release cycle. This can become pretty expensive over time. A cheaper (free) option would be to distribute this code through conda-forge. I recently went through this experience and it isn't too bad at all!

See instructions here:
https://github.com/conda-forge/staged-recipes

When you are on the TravisCI site, it will show that Mac OSx is included in the $69 USD per month plan. However, this is NOT true. I recently went through the process of finding this out the hard way! I opened a support issue with TravisCI and they did not reimburse me or give me OSx credit as the image shows.

![image](https://user-images.githubusercontent.com/18449075/105338825-96a21900-5ba1-11eb-9e50-8ef57eb3705c.png)

See this page for correct billing:
https://docs.travis-ci.com/user/billing-overview

Related Issues
https://github.com/mrjbq7/ta-lib/pull/343

**Comment by mrjbq7** [comment]
Closing old issue.
