### ISSUE TITLE
 Awesome Oscillator

### ISSUE THREAD

**Issue by YuriyTigiev** [TA-Lib/ta-lib-python#394]
Do you plan to add an Awesome Oscillator?

**Comment by mrjbq7** [comment]
This project is just a wrapper for the TA-Lib C library, so I would prefer not to add any new indicators that aren’t supported by the underlying library.

**Comment by YuriyTigiev** [comment]
Is it a correct link ? https://www.ta-lib.org/hdr_dev.html   more links are broken

**Comment by mrjbq7** [comment]
Yes
