### ISSUE TITLE
TA_Lib not found in brez

### ISSUE THREAD

**Issue by Anaschouihdi** [TA-Lib/ta-lib-python#399]
Hello, 

I am trying to download TA-Lib and it seems the formulae is wrong. I am on MAC OS Catalin. thx for your help 
<img width="567" alt="Screenshot 2021-02-19 at 18 46 35" src="https://user-images.githubusercontent.com/25079411/108547785-3b239200-72eb-11eb-8999-1dc4ff226836.png">

**Comment by mrjbq7** [comment]
Maybe some kind of homebrew installation issue.

The formula is here:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/ta-lib.rb

**Comment by Anaschouihdi** [comment]
Thank you, as tried brew install and the formula in the file you gave me and I get the same error ...

**Comment by mrjbq7** [comment]
Perhaps work with the homebrew project to fix it, sorry. 

Also, maybe try “brew doctor”.
