### ISSUE TITLE
Exception: TA_MACD function failed with error code 5119: Unknown Error

### ISSUE THREAD

**Issue by jzx20061010** [TA-Lib/ta-lib-python#425]
While caluclating the factor with pandas,I found the problem.
What I used:
groupby , apply , 
for time in range(5,60):
       df[f"MACD_macd_{time}"],df["MACD_macdsignal"],df["MACD_macdhist"] = talib.MACD(close, fastperiod=time//2, slowperiod=time, signalperiod=time//3)
The error happened

**Comment by mrjbq7** [comment]
Could you provide a test case that I can use to reproduce this?  I have not seen that error before.

**Comment by mrjbq7** [comment]
Closing old issue.
