### ISSUE TITLE
TA_EMA function failed with error code 2: Bad Parameter (TA_BAD_PARAM)

### ISSUE THREAD

**Issue by mert-donmez** [TA-Lib/ta-lib-python#502]
I calculate value_ by giving value to the length, but when I give the 1, I get the error in the title

    df[value_]=ta.EMA(df , length)

There is no problem when I give a value greater than 2

**Comment by Poursaeid** [comment]
Hi , I have the same problem.
did you find any solution for this ?

**Comment by mert-donmez** [comment]
> Hi , I have the same problem. did you find any solution for this ?

Sorry for the late response. If you continue to give the Length value as 1, you will continue to receive an error. However, using df['close'] instead of trying to give the Length value as 1 will solve the problem. The EMA1 value will already be equal to the last closing price.

**Comment by mrjbq7** [comment]
I don't think you want to pass length, you want to pass the period for the EMA calculation, and you probably don't just want the defaults to 30, I think.
