### ISSUE TITLE
TA-Lib Documentation is unavailable 

### ISSUE THREAD

**Issue by jerry-z** [TA-Lib/ta-lib-python#547]
Hello,

All external links to http://tadoc.org from https://mrjbq7.github.io/ta-lib/doc_index.html are not working, as their website seems to be down. Is there any other way to view the direct documentation/formulas associated associated with the technical indicators?

**Comment by trufanov-nok** [comment]
Btw, the latest webarchive copy of tadoc.org is available for browsing here: https://web.archive.org/web/20220708211950/https://tadoc.org/

**Comment by RonySuridata** [comment]
https://web.archive.org/web/20220625220531/https://tadoc.org/indicator/bbands.htm
this doesn't exist.
Is there any documentation for this library? Not just a few examples that don't explain how to use the functions differently.

**Comment by trufanov-nok** [comment]
that's wierd.
Use the older snapshot: https://web.archive.org/web/20220501064852/http://tadoc.org/indicator/BBANDS.htm
or search the web.archive.org for http://tadoc.org/indicator/BBANDS.htm to get other available backups.

**Comment by pmargara** [comment]
There are plans to implement a long term solution for this issue? Users cannot use web archive forever

**Comment by pmargara** [comment]
I understand that you don't manage that website, but that documentation is quite an important piece also for the documentation of this project since is complementing it and completing it. 
From my point of view, as a user, clone the information could be enough to have back the documentation in a consistent state. But I also perfectly undestand your point of view.

**Comment by HarryneZoumi** [comment]
> We don’t maintain that website, sorry. Long term we could clone the information maybe and support a fork?

Has anyone tried to get in touch and notify them that their entire community forum is down? lol 

Either way, their docs site is mostly linking to Investopedia. I would happy to update the relevant links via PR if that's suitable?

**Comment by trufanov-nok** [comment]
TA-Lib is a C library which is a ~20 year old project created by Mario Fortier, and the last commit of its author was roughly 10 years ago. It's not funded, not sponsored and its python wrapper is maintained by enthusiasts. The original C lib is not maintained at all. I'm quite surprised that any website about it is still alive and wonder who pays for that or maintain them... The " entire community forum" is basically here.

**Comment by mario4tier** [comment]
Mario Fortier here. 

After TA-Lib did reach "enough maturity for what I needed" I did stop working on it.

I am not actively working on TA-Lib anymore and do not plan to resume... but I am very glad of seeing that the community took over and it seems it will survive me. Thank you guys, I greatly appreciate.

That being said, I think I can allocate a few days (by mid-2023) to at least salvage the documentation on GitHub and redirect the website to it, such that it can be hosted for free on long term.

I will coordinate privately with John to decide how to best handle this and avoid confusion (thinking to put it all in this repository).

**Comment by mrjbq7** [comment]
We have mirrored the current ta-doc website to:

https://ta-lib.github.io/ta-doc/

**Comment by mrjbq7** [comment]
Closing old issue.
