### ISSUE TITLE
Win 10 - Can't Import Ta-lib even succesfully installed

### ISSUE THREAD

**Issue by KKKRIANGKRAI** [TA-Lib/ta-lib-python#556]
Hello all,

My first time here. Could anyone help me?

I installed the Ta-lib using the whl file TA_Lib-0.4.24-cp310-cp310-win_amd64.whl
and it shows 'Successfully installed TA-Lib-0.4.24'
When I try to import talib into jupyter notebook, an error occurs:
ModuleNotFoundError: No module named 'talib'

I also tried running 'import talib' in the terminal, no error
Can anyone help me with this issue?

**Comment by mrjbq7** [comment]
It's important that you install the whl into the same python interpreter you want to use it with.

Sometimes if you install with ``pip install``, the pip is linked to a different python than ``python`` is.

So, I suggest trying to ``python -m pip install`` and then immediately try ``python`` to ``import talib``.

**Comment by mrjbq7** [comment]
Closing old issue.
