### ISSUE TITLE
Bug Numpy > 1.20.0

### ISSUE THREAD

**Issue by nsadigova** [TA-Lib/ta-lib-python#561]
Can not import talib if I Numpy version >= 1.20.0, for numpy==1.19.5 works fine. 

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by mw66** [comment]
Talib 0.4.24 works fine.

**Comment by mrjbq7** [comment]
I've been using latest numpy for years, it works fine for me...
