### ISSUE TITLE
symbol not found in flat namespace '_TA_ACOS'

### ISSUE THREAD

**Issue by Yktrcn** [TA-Lib/ta-lib-python#563]
I recently bought a Mac Pro with m2 chip. I installed pycharm and python 3.11.

To run my script I need ta-lib module.

i installed talib with pip and brew as well. But none of them worked. Also I searched for similar error on the net. I tried everything but none of them worked. I am really confused.

Traceback (most recent call last): File "/Users/*****/PycharmProjects/pythonProject/main.py", line 5, in import talib as ta File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/talib/init.py", line 93, in from ._ta_lib import ( ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/talib/_ta_lib.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_TA_ACOS'

I changed the interpreter to 3.9 but it didn't work. Also I tried in virtual environment and local both but didn't work as well. I ran out of options. Hopefully someone can help me.

**Comment by mrjbq7** [comment]
Is your brew installing ARM64 packages?Did you use “python3.11 -m pip install”?On Nov 20, 2022, at 5:14 AM, Yktrcn ***@***.***> wrote:﻿
I recently bought a Mac Pro with m2 chip. I installed pycharm and python 3.11.
To run my script I need ta-lib module.
i installed talib with pip and brew as well. But none of them worked. Also I searched for similar error on the net. I tried everything but none of them worked. I am really confused.
Traceback (most recent call last): File "/Users/*****/PycharmProjects/pythonProject/main.py", line 5, in import talib as ta File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/talib/init.py", line 93, in from ._ta_lib import ( ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/talib/_ta_lib.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_TA_ACOS'
I changed the interpreter to 3.9 but it didn't work. Also I tried in virtual environment and local both but didn't work as well. I ran out of options. Hopefully someone can help me.

**Comment by Yktrcn** [comment]
How can i be sure that brew installs arm64 packages? I specified nothing in the beginning. After that i saw couple posts trying x86 packages which was for m1 chips. It didn’t work too

**Comment by mrjbq7** [comment]
The short version is you can do $ which brewAnd if it’s in /usr it’s x86.64 and if it’s in /opt it’s ARM64. Also, You should be able to run “file” on the Ta-Lib C library to see what it was built with. There is no reason this wouldn’t support M2 or python 3.11, except an installation issue. On Nov 20, 2022, at 8:41 AM, Yktrcn ***@***.***> wrote:﻿
How can i be sure that brew installs arm64 packages? I specified nothing in the beginning. After that i saw couple posts trying x86 packages which was for m1 chips. It didn’t work too

**Comment by Yktrcn** [comment]
Thanks for your help. Although I am newbie I am going step by step.

I opened a terminal and wrote where brew and here is the results:
/opt/homebrew/bin/brew
/usr/local/bin/brew

Does this might be the reason? There are two brews in my Mac?

**Comment by mrjbq7** [comment]
Right, they can coexist to install Intel versions of software. But if you use python 3.11 native on apple silicon, you want to install and use the ARM64 packages using the /opt brew On Nov 20, 2022, at 9:29 AM, Yktrcn ***@***.***> wrote:﻿
Thanks for your help. Although I am newbie I am going step by step.
I opened a terminal and wrote where brew and here is the results:
/opt/homebrew/bin/brew
/usr/local/bin/brew
Does this might be the reason? There are two brews in my Mac?

**Comment by vedant17** [comment]
Hello @mrjbq7 

I am facing a similar issue and I followed all the steps in this thread. I used 

arch -arm64 brew install ta-lib to install the arm64 version. I'm still getting the same issue as above

**Comment by mrjbq7** [comment]
You shouldn’t need to use arch -ARM64 if you are using brew installed natively in /opt. That kinda implies you have a mixed architecture system. Is the python3.11 that you are using Intel or apple silicon?

This library works great in Intel and apple silicon versions, can run in Rosetta and natively. Most of these issues are devops issues where you just have to match the architecture properly. I recommend clean ARM64 everything which means avoiding /usr homebrew and using /opt homebrew as long as you don’t need mixed architectures.

**Comment by mrjbq7** [comment]
Closing old issue.

**Comment by Zijun-Tang** [comment]
> Hello @mrjbq7
> 
> I am facing a similar issue and I followed all the steps in this thread. I used
> 
> arch -arm64 brew install ta-lib to install the arm64 version. I'm still getting the same issue as above

Hi, did you solve your problem? I'm facing the same problem

**Comment by mrjbq7** [comment]
Make sure all your architectures match.

It’s easy and simple when they do.

**Comment by Zijun-Tang** [comment]
How to match the architectures? When I write which brew in terminal, the result is: /opt/homebrew/bin/brew. What can I do next? Thank you!

**Comment by mrjbq7** [comment]
```
$ which brew
/opt/homebrew/bin/brew

$ brew install ta-lib

$ file $(brew --prefix ta-lib)/lib/libta_lib.dylib 
/opt/homebrew/opt/ta-lib/lib/libta_lib.dylib: Mach-O 64-bit dynamically linked shared library arm64

$ file $(which python3.11)
/opt/homebrew/opt/python@3.11/bin/python3.11: Mach-O 64-bit executable arm64

$ python3.11 -m pip install ta-lib

$ python3.11 -c "import talib; print(talib.__version__)"
0.4.28
```

**Comment by Zijun-Tang** [comment]
My result is same with yours until the last command. When I write python3.11 -c "import talib; print(talib.__version__)", the result is still: ImportError: dlopen(/opt/homebrew/lib/python3.11/site-packages/talib/_ta_lib.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_TA_ACOS'

**Comment by mrjbq7** [comment]
Have you tried pip uninstall and then reinstall?

**Comment by Zijun-Tang** [comment]
yes, the problem is still there

**Comment by mrjbq7** [comment]
Do you also have ta-lib installed in /usr homebrew with Intel? Maybe it’s picking that one one firstOn Feb 13, 2024, at 9:22 PM, Zijun-Tang ***@***.***> wrote:﻿
yes, the problem is still there

**Comment by Zijun-Tang** [comment]
How to see if I installed ta-lib in /usr homebrew with Intel?

**Comment by mrjbq7** [comment]
In the README did you try setting these to force it to use the ARM64 one installed:$ export TA_INCLUDE_PATH="$(brew --prefix ta-lib)/include"
$ export TA_LIBRARY_PATH="$(brew --prefix ta-lib)/lib"
Set those and then run pip uninstall / reinstalll On Feb 13, 2024, at 9:31 PM, Zijun-Tang ***@***.***> wrote:﻿
How to see if I installed ta-lib in /usr homebrew with Intel?

**Comment by Zijun-Tang** [comment]
When writting (export TA_INCLUDE_PATH="$(brew --prefix ta-lib)/include") and (export TA_LIBRARY_PATH="$(brew --prefix ta-lib)/lib") in terminal, they don't have results, right? 
Then I write:
brew uninstall ta-lib
brew install ta-lib 
python3.11 -m pip uninstall ta-lib
python3.11 -m pip install ta-lib
python3.11 -c "import talib; print(talib.__version__)"
The result is still: symbol not found in flat namespace '_TA_ACOS'

**Comment by mrjbq7** [comment]
I think you have an Intel version of TA-lib installed and it’s finding it firsthttps://github.com/TA-Lib/ta-lib-python/blob/master/setup.py#L29You can see it looks under /usr alsoOn Feb 13, 2024, at 9:53 PM, Zijun-Tang ***@***.***> wrote:﻿
When writting (export TA_INCLUDE_PATH="$(brew --prefix ta-lib)/include") and (export TA_LIBRARY_PATH="$(brew --prefix ta-lib)/lib") in terminal, they don't have results, right?
Then I write:
brew uninstall ta-lib
brew install ta-lib
python3.11 -m pip uninstall ta-lib
python3.11 -m pip install ta-lib
python3.11 -c "import talib; print(talib.version)"
The result is still: symbol not found in flat namespace '_TA_ACOS'

**Comment by Zijun-Tang** [comment]
When I write ls /usr/local/include in terminal, there's no result, does it mean I don't have Intel version of TA-lib installed?

**Comment by mrjbq7** [comment]
I know you're probably learning and frustrated trying to fix this, but seriously, are there any ta-lib files under ``/usr`` is something you should learn how to do:

```
$ cd /usr

$ find . | grep libta_lib
./local/Cellar/ta-lib/0.4.0/lib/libta_lib.dylib
./local/Cellar/ta-lib/0.4.0/lib/libta_lib.a
./local/Cellar/ta-lib/0.4.0/lib/libta_lib.0.dylib
./local/lib/libta_lib.dylib
./local/lib/libta_lib.a
./local/lib/libta_lib.0.dylib
```

**Comment by zapgroupdev** [comment]
> ```
> $ which brew
> /opt/homebrew/bin/brew
> 
> $ brew install ta-lib
> 
> $ file $(brew --prefix ta-lib)/lib/libta_lib.dylib 
> /opt/homebrew/opt/ta-lib/lib/libta_lib.dylib: Mach-O 64-bit dynamically linked shared library arm64
> 
> $ file $(which python3.11)
> /opt/homebrew/opt/python@3.11/bin/python3.11: Mach-O 64-bit executable arm64
> 
> $ python3.11 -m pip install ta-lib
> 
> $ python3.11 -c "import talib; print(talib.__version__)"
> 0.4.28
> ```

my path is usr/local/bin/brew, is this incorrect?

**Comment by mrjbq7** [comment]
Well it all depends.

If you are using an Apple Silicon (arm64) computer, then you have two options:

1) running all python and ta-lib using Intel (x64) binaries which includes brew in /usr/local.

2) running all python and ta-lib using Apple Silicon (arm64) native binaries which includes brew in /opt/local.

You can mix these accidentally using for example ``arch -x86_64 brew install ta-lib`` and that will be confusing if you don't keep your brew's separate.
