### ISSUE TITLE
Can't install ta-lib in setup.py

### ISSUE THREAD

**Issue by nikneural** [TA-Lib/ta-lib-python#564]
Hi, i want to install ta-lib in setup.py, when i install my github repo, but it gives error:
Building wheel for ta-lib (setup.py) ... error
ERROR: Failed building wheel for ta-lib
In my setup.py:
           install_requires=[dependencies,"ta-lib @ git+https://git@github.com/mrjbq7/ta-lib.git@TA_Lib-0.4.19#egg=ta-lib"]
Thanks in advance if you know how to do it

**Comment by SomethingUseful** [comment]
I had issues on Mac Big Sur until I reinstalled command line tools and updated clang ...

% sudo rm -rf /Library/Developer/CommandLineTools
% sudo xcode-select --install
% clang --version
Apple clang version 12.0.5 (clang-1205.0.22.11)

THEN...
$ pip3 install ta-lib
Collecting ta-lib
  Using cached TA-Lib-0.4.25.tar.gz (271 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.10/site-packages (from ta-lib) (1.24.0)
Building wheels for collected packages: ta-lib
  Building wheel for ta-lib (pyproject.toml) ... done
  Created wheel for ta-lib: filename=TA_Lib-0.4.25-cp310-cp310-macosx_11_0_x86_64.whl size=450718 sha256=d793bcd939d8b4c43efa00359ae45207e18d5d622a3d794f8da1fef12279d23b
  Stored in directory: /Users/xxxxxx/Library/Caches/pip/wheels/ac/12/d0/2ea05cfb5b9c4bbf47b45dd93ff5baed86ddb85c748166cb6f
Successfully built ta-lib
Installing collected packages: ta-lib
Successfully installed ta-lib-0.4.25
