### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by abstractumx** [TA-Lib/ta-lib-python#569]
error: command 'x86_64-linux-gnu-gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for TA-Lib

**Comment by abstractumx** [comment]
shuld I install also SWING to use TA-LIB?

**Comment by mrjbq7** [comment]
90% this means you don’t have TA-Lib C library installed. Follow the directions in the README. On Dec 10, 2022, at 7:12 AM, abstractumx ***@***.***> wrote:﻿
  error: command 'x86_64-linux-gnu-gcc' failed: No such file or directory
  [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for TA-Lib

**Comment by mrjbq7** [comment]
If you mean SWIG? No it’s not required when using this TA-Lib wrapper. On Dec 10, 2022, at 7:15 AM, abstractumx ***@***.***> wrote:﻿
shuld I install also SWING to use TA-LIB?

**Comment by trufanov-nok** [comment]
Perhaps the compiler itself is missing. Try
`sudo apt install gcc`
or
`sudo apt install build-essential`

**Comment by SomethingUseful** [comment]
I had issues on Mac Big Sur until I reinstalled command line tools and updated clang ...

% sudo rm -rf /Library/Developer/CommandLineTools
% sudo xcode-select --install
% clang --version
Apple clang version 12.0.5 (clang-1205.0.22.11)

THEN...
$ pip3 install ta-lib
Collecting ta-lib
  Using cached TA-Lib-0.4.25.tar.gz (271 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.10/site-packages (from ta-lib) (1.24.0)
Building wheels for collected packages: ta-lib
  Building wheel for ta-lib (pyproject.toml) ... done
  Created wheel for ta-lib: filename=TA_Lib-0.4.25-cp310-cp310-macosx_11_0_x86_64.whl size=450718 sha256=d793bcd939d8b4c43efa00359ae45207e18d5d622a3d794f8da1fef12279d23b
  Stored in directory: /Users/xxxxxx/Library/Caches/pip/wheels/ac/12/d0/2ea05cfb5b9c4bbf47b45dd93ff5baed86ddb85c748166cb6f
Successfully built ta-lib
Installing collected packages: ta-lib
Successfully installed ta-lib-0.4.25
