### ISSUE TITLE
Integration of Indicator ADR (Average Day Range)

### ISSUE THREAD

**Issue by SeroBass** [TA-Lib/ta-lib-python#575]
May I ask if it is possible to integrate this indicator into the library? If you wish, I can provide you with the strategy.py-file of freqtrade. There I have an implementation.

**Comment by mrjbq7** [comment]
We are in the process of maintaining the TA-Lib C library. That is where
new indicators for this should go, and then this module can wrap it.

I have so far resisted adding indicators here that are not in TA-Lib.

**Comment by mrjbq7** [comment]
Feel free to open this issue on https://github.com/TA-Lib/ta-libOn Jan 22, 2023, at 12:38 PM, SeroBass ***@***.***> wrote:﻿
May I ask if it is possible to integrate this indicator into the library? If you wish, I can provide you with the strategy.py-file of freqtrade. There I have an implementation.
