### ISSUE TITLE
The adx calculation formula is wrong.

### ISSUE THREAD

**Issue by vnvdev** [TA-Lib/ta-lib-python#576]
I use MT5 and Talib to calculate ADX, however, produce 2 completely different results!

**Comment by mrjbq7** [comment]
Can you provide an example of the data and the two outputs, showing which one you think should be correct?On Jan 24, 2023, at 5:27 PM, Vũ Nhật Vượng ***@***.***> wrote:﻿
I use MT5 and Talib to calculate ADX, however, produce 2 completely different results!

**Comment by vnvdev** [comment]
https://github.com/vnvdev/adx-calculate-same-mt5/blob/main/adx.py
Here is the code that compares my 2 outputs and the adx on talib. For talib, adx is only true on adx 14, the rest of the lengths are wrong

**Comment by vnvdev** [comment]
The reason I want to use talib is because it is faster than my code, but the results with adx7, adx21, adx other than 14 all give wrong results compared to mt5

**Comment by vnvdev** [comment]
As for my code all adx are correct with mt5

**Comment by vnvdev** [comment]
Hope you fix it soon

**Comment by trufanov-nok** [comment]
Have you tried `talib.set_compatibility(1)` before ADX call?

**Comment by vnvdev** [comment]
> Have you tried `talib.set_compatibility(1)` before ADX call?

What is this?

**Comment by trufanov-nok** [comment]
https://stackoverflow.com/questions/74896623/python-ema-calculation-using-talib-and-pandas-ewn-different-from-tradingview

> > Have you tried `talib.set_compatibility(1)` before ADX call?
> 
> What is this?

**Comment by vnvdev** [comment]
> https://stackoverflow.com/questions/74896623/python-ema-calculation-using-talib-and-pandas-ewn-different-from-tradingview
> 
> > > Have you tried `talib.set_compatibility(1)` before ADX call?
> > 
> > 
> > What is this?

This not work with adx

**Comment by vnvdev** [comment]
Im fixed it with my Cython code, it very fast same talib. Here is my code
https://github.com/vnvdev/adx_faster

**Comment by pablobrunetti** [comment]
@vnvdev, is this code work with Plus Directional Indicator(PLUS_DI ) and Minus Directional Indicator(MINUS_DI)?
I had the same problem.

**Comment by vnvdev** [comment]
The code only calculates the adx index, the other indicators do not
