### ISSUE TITLE
Polars DeprecationWarning: `columns`

### ISSUE THREAD

**Issue by ITachy0n** [TA-Lib/ta-lib-python#586]
Polars deprecates 'columns' in the initialization of dataframes. It should be changed to 'schema'.

polars: 0.16.14
ta-lib: 0.4.25
```
import polars as pl
from talib import abstract 

df = pl.DataFrame([1,2,3,4,5,6,7,8,9,10], schema = ['close'])      #before: columns = ['close']
df_bbands = abstract.BBANDS(df)
```
```DeprecationWarning: `columns` is deprecated as an argument to `__init__`; use `schema` instead.```
<br>

I guess the code leading to the warning is line 378 in  https://github.com/TA-Lib/ta-lib-python/blob/2e449cbb5d09dc5976558d221c47e19286b38e2f/talib/_abstract.pxi#L372-L378

**Comment by mrjbq7** [comment]
Fixed in bc1841bdfd2bf8f4cf25d3a470acf1cd47603752.
