### ISSUE TITLE
ta-lib on mac m1

### ISSUE THREAD

**Issue by wilker06** [TA-Lib/ta-lib-python#587]
I used and liked ta-lib on Mac m1 with python3.10.
For some reason, I moved on to 3.11. Unfortunately, I could not make ta-lib running again.
For example, applying WMA the error '... WMA not found in __init__' pops up.
Could you kindly advise how to fix th issue.

**Comment by mrjbq7** [comment]
Follow the directions in the README. $ python3.11 -m pip install ta-libMake sure the architectures match. On Mar 26, 2023, at 10:16 PM, wilker06 ***@***.***> wrote:﻿
I used and liked ta-lib on Mac m1 with python3.10.
For some reason, I moved on to 3.11. Unfortunately, I could not make ta-lib running again.
For example, applying WMA the error '... WMA not found in init' pops up.
Could you kindly advise how to fix th issue.

**Comment by wilker06** [comment]
I tried everything recommended in readme ....
- arch -arm64 brew install ta-lib: installs version 0.4.0
- python3.11  -m pip install --no-cache-dir ta-lib: installs 0.4.25 with the comment 'Successfully installed ta-lib-0.4.25'
Using WMA() in a method programmed with PyCharm 2022.3.3 (Professional Edition) WMA() I am notified "Cannot find reference 'WMA' in '__init__.py'", but __function_groups__ = { .. } include 'WMA' in group 'Overlap Studies'

Ignoring this and running any code that include ta-lib import and a method with WMA, it ends up in a lengthy error message even if the method with WMA is not called.
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)

**Comment by wilker06** [comment]
Another comment: most common is the message:
ImportError: dlopen(/Users/.../GitHub/Trading/venv/lib/python3.11/site-packages/talib/_ta_lib.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_TA_ACOS'

**Comment by mrjbq7** [comment]
Sounds like a mixed architecture issue. You should uninstall it and reinstall. You shouldn’t need to arch -arm64 if brew is native in /opt.Instead of pycharm and the virtual env, just get it working in the terminal first. It’s 100% works and supported. On Mar 27, 2023, at 2:11 AM, wilker06 ***@***.***> wrote:﻿
Another comment: most common is the message:
ImportError: dlopen(/Users/.../GitHub/Trading/venv/lib/python3.11/site-packages/talib/_ta_lib.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_TA_ACOS'

**Comment by wilker06** [comment]
Hi John,

I followed your advice to build a new, clear python application:

1. I deleted all python packages, removed everything about python - using the terminal
2. Reinstalled package python 3.10, ib_insync, ….
3. Run simple test code in PyCharm:

	import talib as ta

	print('soso‘)

It ends up with the error:

Traceback (most recent call last):
  File "/Users/…/GitHub/Trading_310/test.py", line 1, in <module>
    import talib as ta
  File "/Users/.../GitHub/Trading_310/venv/lib/python3.10/site-packages/talib/__init__.py", line 93, in <module>
    from ._ta_lib import (
ImportError: dlopen(/Users/... /GitHub/Trading_310/venv/lib/python3.10/site-packages/talib/_ta_lib.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace ‚_TA_ACOS'

4. Running the test code with the terminal.

Last login: Thu Mar 30 20:26:49 on ttys000
cd '/Users/... /GitHub/Trading_310/' && '/usr/local/bin/python3'  '/Users/... /GitHub/Trading_310/test.py'  && echo Exit status: $? && exit 1
... @MBP-von-Kersten ~ % cd '/Users/... /GitHub/Trading_310/' && '/usr/local/bin/python3'  '/Users/... /GitHub/Trading_310/test.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/... /GitHub/Trading_310/test.py", line 1, in <module>
    import talib as ta
ModuleNotFoundError: No module named 'talib'
... @MBP-von-Kersten Trading_310 % 

I attach also a screenshot of the pyCHharm Project window


Any idea?
Thank you in advance for your kind advice!

Best regards,

Kersten

> Am 27.03.2023 um 15:31 schrieb John Benediktsson ***@***.***>:
> 
> 
> Sounds like a mixed architecture issue. You should uninstall it and reinstall. You shouldn’t need to arch -arm64 if brew is native in /opt.Instead of pycharm and the virtual env, just get it working in the terminal first. It’s 100% works and supported. On Mar 27, 2023, at 2:11 AM, wilker06 ***@***.***> wrote:﻿
> Another comment: most common is the message:
> ImportError: dlopen(/Users/.../GitHub/Trading/venv/lib/python3.11/site-packages/talib/_ta_lib.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_TA_ACOS'
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

￼

**Comment by mrjbq7** [comment]
Have you tried:

```
# check that it's using ``/opt`` which is for arm64 builds

$ which brew
/opt/homebrew/bin/brew

$ brew install ta-lib
$ export TA_INCLUDE_PATH="$(brew --prefix ta-lib)/include"
$ export TA_LIBRARY_PATH="$(brew --prefix ta-lib)/lib"
$ python3.11 -m pip install ta-lib
```

**Comment by wilker06** [comment]
Hi John,

I got it work again, found some Python traces from earlier installations, very deep at the system.

Kind regards

Kersten

**Comment by iKpoxa** [comment]
here is what worked for me (Apple M2 Max, Sonoma 14.4)

python3.11 pip uninstall ta-lib

export HOMEBREW_PREFIX=/opt/homebrew #set to your homebrew prefix
export CPPFLAGS="$CPPFLAGS -Xpreprocessor -fopenmp"
export CFLAGS="$CFLAGS -I/usr/local/opt/libomp/include"
export CXXFLAGS="$CXXFLAGS -I/usr/local/opt/libomp/include"
export LDFLAGS="$LDFLAGS -Wl,-rpath,/usr/local/opt/libomp/lib -L/usr/local/opt/libomp/lib -lomp"


python3.11 -m pip install --no-cache-dir ta-lib

**Comment by wilker06** [comment]
@iKpoxa: thank you for the advice.
As I already wrote on Apr 7, 2023 I followed John's advice and got it work again.
Works fine since!

**Comment by nyssance** [comment]
> 您是否尝试过：
> 
> ```
> # check that it's using ``/opt`` which is for arm64 builds
> 
> $ which brew
> /opt/homebrew/bin/brew
> 
> $ brew install ta-lib
> $ export TA_INCLUDE_PATH="$(brew --prefix ta-lib)/include"
> $ export TA_LIBRARY_PATH="$(brew --prefix ta-lib)/lib"
> $ python3.11 -m pip install ta-lib
> ```

Not work for M1 and poetry install. code can run, but code hints.(Pycharm/VSCode)
