### ISSUE TITLE
need help with error. having trouble with installing talib.

### ISSUE THREAD

**Issue by reborn0904** [TA-Lib/ta-lib-python#596]
i downloaded ta-lib on windows and using anaconda prompt. and when i try to install the talib file im getting this error  error: subprocess-exited-with-error,  × Building wheel for TA-Lib (pyproject.toml) did not run successfully.  ERROR: Failed building wheel for TA-Lib ERROR: Could not build wheels for TA-Lib, which is required to install pyproject.toml-based projects. when i put this error into chatgpt to find out whats the issue its states that im missing a ta.libc.h file. so ibe  beeen stuck trying to fix this issue for hours. i have python 3.8.16 64bit, im using anaconda i have powershell, i have the program spyder python that was installed. i have the talib file that i downloaded from the official website and i tried the un official sub website both didnt work. i dont know what im doing wrong?

**Comment by mrjbq7** [comment]
Did you try installing the unofficial wheel ? It is self-contained. 

That error is because you need the underlying C library.

**Comment by reborn0904** [comment]
where can i go to download the unofficial wheel and thank you for emailing
me. i appreciate the help

**Comment by mrjbq7** [comment]
There's more information in the project README, but here's the link:

> You might also try these unofficial windows binaries for both 32-bit and 64-bit:
>
> https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib

**Comment by cgohlke** [comment]
> There's more information in the project README, but here's the link:
> 
> > You might also try these unofficial windows binaries for both 32-bit and 64-bit:
> > https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib

TA-Lib wheels for Windows are now provided at https://github.com/cgohlke/talib-build

**Comment by Sandy4321** [comment]
cool
https://github.com/cgohlke/talib-build
but how to use it?
in any case I do have windows 11 and 64 bits cpu 
Python 3.10.11 
what file to use from 
https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib
from 
and how use it to install ta-lib ?

**Comment by DoozyDoz** [comment]
> cool https://github.com/cgohlke/talib-build but how to use it? in any case I do have windows 11 and 64 bits cpu Python 3.10.11 what file to use from https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib from and how use it to install ta-lib ?

exactly, the readme show nothing the batch cmd file also just adds a corrupt talib.zip file, no help

**Comment by LucaZiegler** [comment]
> > There's more information in the project README, but here's the link:
> > > You might also try these unofficial windows binaries for both 32-bit and 64-bit:
> > > https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib
> 
> TA-Lib wheels for Windows are now provided at https://github.com/cgohlke/talib-build

**Error with amd64:**
ERROR: TA_Lib-0.4.28-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.

**Error with 32bit:**
ERROR: TA_Lib-0.4.28-cp39-cp39-win32.whl is not a supported wheel on this platform.

**Comment by mrjbq7** [comment]
Closing old issue.
