### ISSUE TITLE
How can we know how many candles data an indicator needs ?

### ISSUE THREAD

**Issue by svax974** [TA-Lib/ta-lib-python#597]
Hello,

I'm wondering how it is possible to know how many historic data are needed for a given indicator.
For instance, how many open/high/low/close elements should I provide to CDL3INSIDE to ensure it will be enough ?
Same for ATR, let's say I'm calling ATR on 14 periods, how many high/low/close should I provide to ensure it works ? It may need some historical data but how many ?

Any light on this is appreciated, thanks !

**Comment by mrjbq7** [comment]
TA-Lib provides lookback functions to calculate that.

```python
>>> import talib.abstract

>>> RSI = talib.abstract.RSI
>>> RSI.parameters
OrderedDict([('timeperiod', 14)])
>>> RSI.lookback
14

>>> RSI.parameters = {'timeperiod': 20}
>>> RSI.lookback
20
```

There are other ways, but that's maybe the easiest.

**Comment by svax974** [comment]
Great ! I'll try that ASAP. Thanks

**Comment by svax974** [comment]
@mrjbq7 
Hi, I'm using TA Lib with data arrays built "by hand" from candlestick data.

I'm having trouble to understand how to get the "most right" values/usage of indicators.

1) Should the data be ordered in a specific way ? I have them ordered from the oldest at the beginning of the arrays to the newest at the end, is that right ?
2) I'm playing with ADX and it seems to be usable with at least periods*2-1 candles data (let's say 27 for an ADX on 14 periods).
If I do it just like this with 27 candles data, I get all NaN values, I have to pass periods*2 (28) to get at least one last value of the array returned is that always the case ? Should I pass lookback+1 values for all indicators ?
3) Last point : if I pass more than periods*2 candles data, without changing any parameter (including the "timeperiod" one), I get different results for the indicator, why ?

Thanks for your help

**Comment by mrjbq7** [comment]
> Should the data be ordered in a specific way ? I have them ordered from the oldest at the beginning of the arrays to the newest at the end, is that right ?

Yes, TA-Lib assumes data is oldest (``close[0]``) to newest (``close[-1]``).

> I'm playing with ADX and it seems to be usable with at least periods2-1 candles data (let's say 27 for an ADX on 14 periods).

Some of the indicators use history that draws from observations older than lookback (for example, EMA). The more data you feed the indicator, the less "error" it will have.

> If I do it just like this with 27 candles data, I get all NaN values, I have to pass periods2 (28) to get at least one last value of the array returned is that always the case ? Should I pass lookback+1 values for all indicators ?

You should at least pass as much data as the lookback required or you won't get any output values. If you just want one latest observation, you can use the streaming api with your entire price dataset and it will use only the lookback required. Keep in mind the history point above for some indicators.

> Last point : if I pass more than periods*2 candles data, without changing any parameter (including the "timeperiod" one), I get different results for the indicator, why ?

Probably the history element.

**Comment by svax974** [comment]
Ok, got the history thing, but if using the streaming api, it would behave just like if I give the function the minimum history it needs, right ?
So, would giving always as much history as we can (or reasonably more than just the requirements) be a good option after all ?
Your lib is really great but I must admit I have hard times getting indicators giving me the same values I get on TradingView.
This is a bit disorienting sometimes.
