### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by martin0** [TA-Lib/ta-lib-python#602]
Hi,

What is the likelihood of supporting Python 3.11 soon?

Kind regards
Martin

**Comment by mrjbq7** [comment]
Does it not?

**Comment by mrjbq7** [comment]
It builds and tests on python 3.11https://github.com/TA-Lib/ta-lib-python/actions/runs/4692690802/jobs/8318715762On Jul 4, 2023, at 11:36 AM, martin0 ***@***.***> wrote:﻿
Hi,
What is the likelihood of supporting Python 3.11 soon?
Kind regards
Martin

**Comment by martin0** [comment]
Thanks for such a quick response...
I am going from a little bit of info, which may be incomplete...
at https://pypi.org/project/TA-Lib/ the Programming Language classifiers stops at Python 3.9
at https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib there is no wheel for 3.11 that I see.
My platform is Windows 11.

Thanks again
Martin

**Comment by mrjbq7** [comment]
I don’t maintain those wheels, in the future we might. However it works
fine on 3.11 and I believe also 3.12.

**Comment by martin0** [comment]
Do you have any advise on how I make the wheel myself?

**Comment by mrjbq7** [comment]
You don’t need to build a wheel, just install 64-but version of TA-Lib C
library and then install this module. The README has some details.

I agree that it would be nicer to package the C library with this install,
but we have hesitated to do that for various reasons. In the future this is
likely to improve.

**Comment by martin0** [comment]
I have previously unzipped the ta-lib-0.4.0-msvc.zip file
But i need something to bridge to Python. I thought that's what the whl file did.

py -m pip install TA-lib fails as per the attached log file.

[talib_install.log](https://github.com/TA-Lib/ta-lib-python/files/11952069/talib_install.log)

**Comment by mrjbq7** [comment]
Follow the README.

You need to build the 64-bit library first, probably. (The binary download
is 32-bit).  Then install this module which is the bridge to python.

**Comment by ling1042133624** [comment]
this works fine.

python -m pip install .\Ta_lib-0.4.25-cp311-cp311-win_amd64.whl

https://drive.google.com/file/d/1j5hniPPSAy8UtLGFDEaNNyYr78oLj3dC/view?usp=drive_link
