### ISSUE TITLE
Unable to find the function definitions of CDLMATHOLD

### ISSUE THREAD

**Issue by mohd-bilal0** [TA-Lib/ta-lib-python#607]
Can anyone tell, where can i find the logic coded for identifying CDLMATHOLD

**Comment by sampanacharya** [comment]
Hi @mohd-bilal0 ,
The code for CDLMATHOLD is on the line 2018, of the file _func.pxi in the following location: ta-lib-python/talib/_func.pxi

**Comment by mohd-bilal0** [comment]
![image](https://github.com/TA-Lib/ta-lib-python/assets/139851170/033a37c4-e660-4fde-a29e-a6144d0d8fe7)
thanks for the comment, but i am  not sure where can i get the logic of  lib.TA_CDLMATHOLD_Lookback and lib.TA_CDLMATHOLD functions being used in the CDLMATHOLD function

**Comment by sampanacharya** [comment]
Hi again @mohd-bilal0 ,
as TA-Lib is a python wrapper written upon TA-Lib written originally in C/C++ the code for it can be found in its source, here linking to the original source :
https://github.com/TA-Lib/ta-lib/blob/main/src/ta_func/ta_CDLMATHOLD.c
