### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by kiratin** [TA-Lib/ta-lib-python#614]
Dear all,

I am having trouble installing the TA-Lib on Ubuntu 22.04. I think I was able to install the dependencies but with pip install ta-lib I am getting the following error. Would anyone kindly help me on this one please? Thanks much in advance!

`error: subprocess-exited-with-error

  × Building wheel for ta-lib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/talib
      copying talib/stream.py -> build/lib.linux-x86_64-cpython-310/talib
      copying talib/deprecated.py -> build/lib.linux-x86_64-cpython-310/talib
      copying talib/abstract.py -> build/lib.linux-x86_64-cpython-310/talib
      copying talib/__init__.py -> build/lib.linux-x86_64-cpython-310/talib
      running build_ext
      building 'talib._ta_lib' extension
      creating build/temp.linux-x86_64-cpython-310
      creating build/temp.linux-x86_64-cpython-310/talib
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/include -I/tmp/pip-build-env-8bzxrejg/normal/lib/python3.10/site-packages/numpy/core/include -I/home/serhat/Trading/my_env/include -I/usr/include/python3.10 -c talib/_ta_lib.c -o build/temp.linux-x86_64-cpython-310/talib/_ta_lib.o
      In file included from /tmp/pip-build-env-8bzxrejg/normal/lib/python3.10/site-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                       from /tmp/pip-build-env-8bzxrejg/normal/lib/python3.10/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                       from /tmp/pip-build-env-8bzxrejg/normal/lib/python3.10/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                       from talib/_ta_lib.c:1092:
      /tmp/pip-build-env-8bzxrejg/normal/lib/python3.10/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
         17 | #warning "Using deprecated NumPy API, disable it with " \
            |  ^~~~~~~
      talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_348_ta_getFuncInfo’:
      talib/_ta_lib.c:51556:48: warning: passing argument 2 of ‘TA_GetFuncInfo’ from incompatible pointer type [-Wincompatible-pointer-types]
      51556 |   __pyx_v_retCode = TA_GetFuncInfo(__pyx_t_1, (&__pyx_v_info));
            |                                               ~^~~~~~~~~~~~~~
            |                                                |
            |                                                TA_FuncInfo **
      In file included from talib/_ta_lib.c:1084:
      /usr/include/ta-lib/ta_abstract.h:211:48: note: expected ‘const TA_FuncInfo **’ but argument is of type ‘TA_FuncInfo **’
        211 |                            const TA_FuncInfo **funcInfo );
            |                            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~
      talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_350_ta_getInputParameterInfo’:
      talib/_ta_lib.c:51832:71: warning: passing argument 3 of ‘TA_GetInputParameterInfo’ from incompatible pointer type [-Wincompatible-pointer-types]
      51832 |   __pyx_v_retCode = TA_GetInputParameterInfo(__pyx_t_1, __pyx_v_idx, (&__pyx_v_info));
            |                                                                      ~^~~~~~~~~~~~~~
            |                                                                       |
            |                                                                       TA_InputParameterInfo **
      In file included from talib/_ta_lib.c:1084:
      /usr/include/ta-lib/ta_abstract.h:442:68: note: expected ‘const TA_InputParameterInfo **’ but argument is of type ‘TA_InputParameterInfo **’
        442 |                                      const TA_InputParameterInfo **info );
            |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
      talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_352_ta_getOptInputParameterInfo’:
      talib/_ta_lib.c:52084:74: warning: passing argument 3 of ‘TA_GetOptInputParameterInfo’ from incompatible pointer type [-Wincompatible-pointer-types]
      52084 |   __pyx_v_retCode = TA_GetOptInputParameterInfo(__pyx_t_1, __pyx_v_idx, (&__pyx_v_info));
            |                                                                         ~^~~~~~~~~~~~~~
            |                                                                          |
            |                                                                          TA_OptInputParameterInfo **
      In file included from talib/_ta_lib.c:1084:
      /usr/include/ta-lib/ta_abstract.h:446:74: note: expected ‘const TA_OptInputParameterInfo **’ but argument is of type ‘TA_OptInputParameterInfo **’
        446 |                                         const TA_OptInputParameterInfo **info );
            |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
      talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_354_ta_getOutputParameterInfo’:
      talib/_ta_lib.c:52374:72: warning: passing argument 3 of ‘TA_GetOutputParameterInfo’ from incompatible pointer type [-Wincompatible-pointer-types]
      52374 |   __pyx_v_retCode = TA_GetOutputParameterInfo(__pyx_t_1, __pyx_v_idx, (&__pyx_v_info));
            |                                                                       ~^~~~~~~~~~~~~~
            |                                                                        |
            |                                                                        TA_OutputParameterInfo **
      In file included from talib/_ta_lib.c:1084:
      /usr/include/ta-lib/ta_abstract.h:450:70: note: expected ‘const TA_OutputParameterInfo **’ but argument is of type ‘TA_OutputParameterInfo **’
        450 |                                       const TA_OutputParameterInfo **info );
            |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
      talib/_ta_lib.c: In function ‘__pyx_f_5talib_7_ta_lib___ta_getFuncHandle’:
      talib/_ta_lib.c:53011:126: warning: passing argument 2 of ‘TA_GetFuncHandle’ from incompatible pointer type [-Wincompatible-pointer-types]
      53011 |   __pyx_t_1 = __pyx_f_5talib_7_ta_lib__ta_check_success(__pyx_n_s_TA_GetFuncHandle, TA_GetFuncHandle(__pyx_v_function_name, (&__pyx_v_handle)), 0); if (unlikely(!__pyx_t_1)) __PYX_ERR(1, 772, __pyx_L1_error)
            |                                                                                                                             ~^~~~~~~~~~~~~~~~
            |                                                                                                                              |
            |                                                                                                                              TA_FuncHandle ** {aka unsigned int **}
      In file included from talib/_ta_lib.c:1084:
      /usr/include/ta-lib/ta_abstract.h:155:52: note: expected ‘const TA_FuncHandle **’ {aka ‘const unsigned int **’} but argument is of type ‘TA_FuncHandle **’ {aka ‘unsigned int **’}
        155 |                              const TA_FuncHandle **handle );
            |                              ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
      x86_64-linux-gnu-gcc: fatal error: Killed signal terminated program cc1
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ta-lib
ERROR: Could not build wheels for ta-lib, which is required to install pyproject.toml-based projects`

**Comment by mrjbq7** [comment]
That typically means not enough RAM. On Sep 15, 2023, at 6:35 PM, kiratin ***@***.***> wrote:﻿
Dear all,
I am having trouble installing the TA-Lib on Ubuntu 22.04. I think I was able to install the dependencies but with pip install ta-lib I am getting the following error. Would anyone kindly help me on this one please? Thanks much in advance!
`error: subprocess-exited-with-error
× Building wheel for ta-lib (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [75 lines of output]
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-cpython-310
creating build/lib.linux-x86_64-cpython-310/talib
copying talib/stream.py -> build/lib.linux-x86_64-cpython-310/talib
copying talib/deprecated.py -> build/lib.linux-x86_64-cpython-310/talib
copying talib/abstract.py -> build/lib.linux-x86_64-cpython-310/talib
copying talib/init.py -> build/lib.linux-x86_64-cpython-310/talib
running build_ext
building 'talib._ta_lib' extension
creating build/temp.linux-x86_64-cpython-310
creating build/temp.linux-x86_64-cpython-310/talib
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/include -I/tmp/pip-build-env-8bzxrejg/normal/lib/python3.10/site-packages/numpy/core/include -I/home/serhat/Trading/my_env/include -I/usr/include/python3.10 -c talib/_ta_lib.c -o build/temp.linux-x86_64-cpython-310/talib/_ta_lib.o
In file included from /tmp/pip-build-env-8bzxrejg/normal/lib/python3.10/site-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
from /tmp/pip-build-env-8bzxrejg/normal/lib/python3.10/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
from /tmp/pip-build-env-8bzxrejg/normal/lib/python3.10/site-packages/numpy/core/include/numpy/arrayobject.h:5,
from talib/_ta_lib.c:1092:
/tmp/pip-build-env-8bzxrejg/normal/lib/python3.10/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
17 | #warning "Using deprecated NumPy API, disable it with " 
|  ^~~~~~~
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_348_ta_getFuncInfo’:
talib/_ta_lib.c:51556:48: warning: passing argument 2 of ‘TA_GetFuncInfo’ from incompatible pointer type [-Wincompatible-pointer-types]
51556 |   __pyx_v_retCode = TA_GetFuncInfo(__pyx_t_1, (&__pyx_v_info));
|                                               ~^~~~~~~~~~~~~~
|                                                |
|                                                TA_FuncInfo **
In file included from talib/_ta_lib.c:1084:
/usr/include/ta-lib/ta_abstract.h:211:48: note: expected ‘const TA_FuncInfo **’ but argument is of type ‘TA_FuncInfo **’
211 |                            const TA_FuncInfo **funcInfo );
|                            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_350_ta_getInputParameterInfo’:
talib/_ta_lib.c:51832:71: warning: passing argument 3 of ‘TA_GetInputParameterInfo’ from incompatible pointer type [-Wincompatible-pointer-types]
51832 |   __pyx_v_retCode = TA_GetInputParameterInfo(__pyx_t_1, __pyx_v_idx, (&__pyx_v_info));
|                                                                      ~^~~~~~~~~~~~~~
|                                                                       |
|                                                                       TA_InputParameterInfo **
In file included from talib/_ta_lib.c:1084:
/usr/include/ta-lib/ta_abstract.h:442:68: note: expected ‘const TA_InputParameterInfo **’ but argument is of type ‘TA_InputParameterInfo **’
442 |                                      const TA_InputParameterInfo **info );
|                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_352_ta_getOptInputParameterInfo’:
talib/_ta_lib.c:52084:74: warning: passing argument 3 of ‘TA_GetOptInputParameterInfo’ from incompatible pointer type [-Wincompatible-pointer-types]
52084 |   __pyx_v_retCode = TA_GetOptInputParameterInfo(__pyx_t_1, __pyx_v_idx, (&__pyx_v_info));
|                                                                         ~^~~~~~~~~~~~~~
|                                                                          |
|                                                                          TA_OptInputParameterInfo **
In file included from talib/_ta_lib.c:1084:
/usr/include/ta-lib/ta_abstract.h:446:74: note: expected ‘const TA_OptInputParameterInfo **’ but argument is of type ‘TA_OptInputParameterInfo **’
446 |                                         const TA_OptInputParameterInfo **info );
|                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_354_ta_getOutputParameterInfo’:
talib/_ta_lib.c:52374:72: warning: passing argument 3 of ‘TA_GetOutputParameterInfo’ from incompatible pointer type [-Wincompatible-pointer-types]
52374 |   __pyx_v_retCode = TA_GetOutputParameterInfo(__pyx_t_1, __pyx_v_idx, (&__pyx_v_info));
|                                                                       ~^~~~~~~~~~~~~~
|                                                                        |
|                                                                        TA_OutputParameterInfo **
In file included from talib/_ta_lib.c:1084:
/usr/include/ta-lib/ta_abstract.h:450:70: note: expected ‘const TA_OutputParameterInfo **’ but argument is of type ‘TA_OutputParameterInfo **’
450 |                                       const TA_OutputParameterInfo **info );
|                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
talib/_ta_lib.c: In function ‘__pyx_f_5talib_7_ta_lib___ta_getFuncHandle’:
talib/_ta_lib.c:53011:126: warning: passing argument 2 of ‘TA_GetFuncHandle’ from incompatible pointer type [-Wincompatible-pointer-types]
53011 |   __pyx_t_1 = __pyx_f_5talib_7_ta_lib__ta_check_success(__pyx_n_s_TA_GetFuncHandle, TA_GetFuncHandle(__pyx_v_function_name, (&__pyx_v_handle)), 0); if (unlikely(!__pyx_t_1)) __PYX_ERR(1, 772, __pyx_L1_error)
|                                                                                                                             ~^~~~~~~~~~~~~~~~
|                                                                                                                              |
|                                                                                                                              TA_FuncHandle ** {aka unsigned int **}
In file included from talib/_ta_lib.c:1084:
/usr/include/ta-lib/ta_abstract.h:155:52: note: expected ‘const TA_FuncHandle **’ {aka ‘const unsigned int **’} but argument is of type ‘TA_FuncHandle **’ {aka ‘unsigned int **’}
155 |                              const TA_FuncHandle **handle );
|                              ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
x86_64-linux-gnu-gcc: fatal error: Killed signal terminated program cc1
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for ta-lib
ERROR: Could not build wheels for ta-lib, which is required to install pyproject.toml-based projects`

**Comment by kiratin** [comment]
That is the fastest accurate response I have ever seen! Thank you so much! Indeed, I increased the memory and it worked.

**Comment by mrjbq7** [comment]
I’m glad it’s working for you!It would be nice to require less RAM for compilation, the best solution is if we can figure out how to build wheels to upload to PyPI. On Sep 15, 2023, at 6:53 PM, kiratin ***@***.***> wrote:﻿
That is the fastest accurate response I have ever seen! Thank you so much! Indeed, I increased the memory and it worked.

**Comment by LucaZiegler** [comment]
Not enough RAM?
I have 16GB and cannot install more in my PC..

**Comment by mrjbq7** [comment]
I think it requires a smidge more than 1GB for compilation at the moment, not sure exactly.

**Comment by ahmedmohamedabdelhadi** [comment]
ERROR: Command errored out with exit status 1:
   command: 'C:\Users\ahmed\anaconda3\python.exe' 'C:\Users\ahmed\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\ahmed\AppData\Local\Temp\tmpcsf9uco2'
       cwd: C:\Users\ahmed\AppData\Local\Temp\pip-install-wp4u5k06\ta-lib_6e5754722d6240559935c47f85e37c5a
  Complete output (20 lines):
  <string>:77: UserWarning: Cannot find ta-lib library, installation may fail.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-39
  creating build\lib.win-amd64-cpython-39\talib
  copying talib\abstract.py -> build\lib.win-amd64-cpython-39\talib
  copying talib\deprecated.py -> build\lib.win-amd64-cpython-39\talib
  copying talib\stream.py -> build\lib.win-amd64-cpython-39\talib
  copying talib\__init__.py -> build\lib.win-amd64-cpython-39\talib
  running build_ext
  building 'talib._ta_lib' extension
  creating build\temp.win-amd64-cpython-39
  creating build\temp.win-amd64-cpython-39\Release
  creating build\temp.win-amd64-cpython-39\Release\talib
  "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ic:\ta-lib\c\include -IC:\Users\ahmed\AppData\Local\Temp\pip-build-env-fpnk9fkr\normal\Lib\site-packages\numpy\core\include -IC:\Users\ahmed\anaconda3\include -IC:\Users\ahmed\anaconda3\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tctalib/_ta_lib.c /Fobuild\temp.win-amd64-cpython-39\Release\talib/_ta_lib.obj
  _ta_lib.c
  talib/_ta_lib.c(1080): fatal error C1083: Cannot open include file: 'ta_libc.h': No such file or directory
  error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for TA-Lib
Failed to build TA-Lib
ERROR: Could not build wheels for TA-Lib which use PEP 517 and cannot be installed directly

**Comment by mrjbq7** [comment]
This is the error:

UserWarning: Cannot find ta-lib library, installation may fail.


I suggest reading the installation section of the README.
