### ISSUE TITLE
Why is Ta-Lib.org suspended?

### ISSUE THREAD

**Issue by SurpriseMF3000** [TA-Lib/ta-lib-python#619]
Hello, does anybody know why the official website of [ta-lib.org](url) is down because of "account suspended"?

**Comment by mrjbq7** [comment]
I'm not sure, @mario4tier ?

**Comment by mario4tier** [comment]
Thanks for bringing this to my attention.

https://ta-lib.org is now working again.

It is now hosted on github and can be more easily edited with markdown by anyone (after pull request approval).

The content is being re-written, so some work-in-progress.
