### ISSUE TITLE
installation error on MacOS

### ISSUE THREAD

**Issue by lca-123** [TA-Lib/ta-lib-python#620]
I install talib on my M2 MacBook, but I have the following error.
#include "ta-lib/ta_defs.h"
               ^~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

please tell me how to handle this problem. thx.

**Comment by mrjbq7** [comment]
If you are building for the same architecture (like aarch64 which is apple silicon) and your brew matches your Python, then it is just:$ brew install ta-lib$ python3 -m pip install ta-libIf you are trying to build for Rosetta on the mac, which targets Intel libraries or Intel python, then it’s typically a problem not having everything match architecture. On Oct 27, 2023, at 2:53 AM, lca ***@***.***> wrote:﻿
I install talib on my M2 MacBook, but I have the following error.
#include "ta-lib/ta_defs.h"
^~~~~~~~~~~~~~~~~~
1 error generated.
error: command '/usr/bin/clang' failed with exit code 1
[end of output]
please tell me how to handle this problem. thx.

**Comment by lca-123** [comment]
I have solve this problem. But thank you all the same.
