### ISSUE TITLE
problem with PVT indicator

### ISSUE THREAD

**Issue by jupiterMJM** [TA-Lib/ta-lib-python#622]
According to the readme, there should be a PVT indicator proposed in talib. However, i can't find it anywhere in this module....

**Comment by mrjbq7** [comment]
I don't think we have PVT implemented, where does it say we do?

**Comment by mrjbq7** [comment]
You can build it pretty easy, something like:

```python
def PVT(c, v):
    return np.cumsum(v[1:] * np.diff(c) / c[:-1])
```

**Comment by mario4tier** [comment]
Moving forward, all requests and further discussion for **new** functions should happen on the [New TA Functions Board]( https://github.com/orgs/TA-Lib/projects/1 )

A reference to this issue has been added to preserve this discussion. Thanks!
