### ISSUE TITLE
TA-Lib Installation error (Windows 11 64 bit, Python 3.11 64 bit, IDE Pycharm), Visual Studio 2022

### ISSUE THREAD

**Issue by kapiltulsan** [TA-Lib/ta-lib-python#623]
Hi Team, 

I am using Windows 11 64 bit, Python 3.11 64 bit, Ide Pycharm, Visual Studio 2022

I followed instuction given below (please note I have 2022 VS and not 2015)

1. Download and Unzip ta-lib-0.4.0-msvc.zip
2. Move the Unzipped Folder ta-lib to C:\
3. Download and Install Visual Studio Community 2015
    Remember to Select [Visual C++] Feature
4. Build TA-Lib Library
    From Windows Start Menu, Start [VS2015 x64 Native Tools Command Prompt]
    Move to C:\ta-lib\c\make\cdr\win32\msvc
    Build the Library nmake
5. Then pip install ta-lib

But no success in installation, getting error in attached text file

[TA-Lib Installation error.txt](https://github.com/TA-Lib/ta-lib-python/files/13399183/TA-Lib.Installation.error.txt)

**Comment by mrjbq7** [comment]
That error indicates that it is not able to find the C library. You can see in setup.py the default location in Windows as well as a way to override that if you have a different location a few lines down:ta-lib-python/setup.py at master · TA-Lib/ta-lib-pythongithub.comAnother reason that it might not work is mixed architectures (32-bit Python and 64-bit library). On Nov 17, 2023, at 10:12 PM, kapiltulsan ***@***.***> wrote:﻿
Hi Team,
I am using Windows 11 64 bit, Pythin 3.11 64 bit, Ide Pycharm, Visual Studio 2022
I followed instuction given below (please note I have 2022 VS and not 2015)

Download and Unzip ta-lib-0.4.0-msvc.zip
Move the Unzipped Folder ta-lib to C:\
Download and Install Visual Studio Community 2015
Remember to Select [Visual C++] Feature
Build TA-Lib Library
From Windows Start Menu, Start [VS2015 x64 Native Tools Command Prompt]
Move to C:\ta-lib\c\make\cdr\win32\msvc
Build the Library nmake
Then pip install ta-lib

But no success in installation, getting error in attached text file
TA-Lib Installation error.txt

**Comment by kapiltulsan** [comment]
> That error indicates that it is not able to find the C library. You can see in setup.py the default location in Windows as well as a way to override that if you have a different location a few lines down:ta-lib-python/setup.py at master · TA-Lib/ta-lib-pythongithub.comAnother reason that it might not work is mixed architectures (32-bit Python and 64-bit library). On Nov 17, 2023, at 10:12 PM, kapiltulsan ***@***.***> wrote:﻿ Hi Team, I am using Windows 11 64 bit, Pythin 3.11 64 bit, Ide Pycharm, Visual Studio 2022 I followed instuction given below (please note I have 2022 VS and not 2015) Download and Unzip ta-lib-0.4.0-msvc.zip Move the Unzipped Folder ta-lib to C:\ Download and Install Visual Studio Community 2015 Remember to Select [Visual C++] Feature Build TA-Lib Library From Windows Start Menu, Start [VS2015 x64 Native Tools Command Prompt] Move to C:\ta-lib\c\make\cdr\win32\msvc Build the Library nmake Then pip install ta-lib But no success in installation, getting error in attached text file TA-Lib Installation error.txt —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thanks issue is resolved, with help of other Post.

**Comment by gooterpul** [comment]
hay bro, i have same problem.
can you tell me how you solved this problem??

**Comment by kapiltulsan** [comment]
Download from
https://drive.google.com/file/d/1j5hniPPSAy8UtLGFDEaNNyYr78oLj3dC/view?usp=sharing

Install by following command
python -m pip install .\Ta_lib-0.4.25-cp311-cp311-win_amd64.whl


Worked for me.


Regards,
Kapil R. Tulsan
http://www.linkedin.com/in/kapiltulsan

**Comment by mrjbq7** [comment]
I really think you guys should build your own software instead of installing random wheels.We could also build wheels as part of this project, but it’s not hard to install these from source either. On Dec 10, 2023, at 7:47 PM, kapiltulsan ***@***.***> wrote:﻿
Download from

https://drive.google.com/file/d/1j5hniPPSAy8UtLGFDEaNNyYr78oLj3dC/view?usp=sharing



Install by following command

python -m pip install .\Ta_lib-0.4.25-cp311-cp311-win_amd64.whl





Worked for me.





Regards,

Kapil R. Tulsan

http://www.linkedin.com/in/kapiltulsan
