### ISSUE TITLE
hello please help me

### ISSUE THREAD

**Issue by Lazymve** [TA-Lib/ta-lib-python#629]
im trying to install ta-lib on a windows 11 comp but every time i do theres an error

│ exit code: 1

╰─> [13 lines of output]

running bdist_wheel

running build

running build_py

creating build

creating build\lib.win-amd64-cpython-311

creating build\lib.win-amd64-cpython-311\talib

copying talib\[abstract.py](https://abstract.py/) -> build\lib.win-amd64-cpython-311\talib

copying talib\[deprecated.py](https://deprecated.py/) -> build\lib.win-amd64-cpython-311\talib

copying talib\[stream.py](https://stream.py/) -> build\lib.win-amd64-cpython-311\talib

copying talib\__init__.py -> build\lib.win-amd64-cpython-311\talib

running build_ext

building 'talib._ta_lib' extension

error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

ERROR: Failed building wheel for TA-Lib

Failed to build TA-Lib

ERROR: Could not build wheels for TA-Lib, which is required to install pyproject.toml-based projects

im on widows 11 have python 11 and have the c++ build tools installed

**Comment by mrjbq7** [comment]
Did you follow the directions in the README?

**Comment by mrjbq7** [comment]
Closing old issue.
