### ISSUE TITLE
Not being able to install wheel file using pip

### ISSUE THREAD

**Issue by Anuj1993** [TA-Lib/ta-lib-python#633]
I am using python 3.11 with a processor type AMD64 and I am trying to install TA-Lib from the wheel file using pip
The name of the wheel file is as follows:
TA_Lib‑0.4.24‑cp310‑cp310‑win_amd64.whl.

But I am getting this error: ERROR: TA_Lib-0.4.24-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

What could be the reason?
PS: I saw a response to another user's exact query in the forum, but I could not completely understand the response.

Kindly Help.

**Comment by mrjbq7** [comment]
That wheel is built for Python 3.10On Jan 4, 2024, at 2:17 AM, Anuj1993 ***@***.***> wrote:﻿
I am using python 3.11 with a processor type AMD64 and I am trying to install TA-Lib from the wheel file using pip
The name of the wheel file is as follows:
TA_Lib‑0.4.24‑cp310‑cp310‑win_amd64.whl.
But I am getting this error: ERROR: TA_Lib-0.4.24-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.
What could be the reason?
PS: I saw a response to another user's exact query in the forum, but I could not completely understand the response.
Kindly Help.
