### ISSUE TITLE
Anaconda Installation Error

### ISSUE THREAD

**Issue by jhvissotto** [TA-Lib/ta-lib-python#636]
![image](https://github.com/TA-Lib/ta-lib-python/assets/19745638/af4e86e4-fb8e-45b1-891c-b9f4f7f3e06c)

And I already downloaded and installed VS C++ too. Nothing worked

**Comment by mrjbq7** [comment]
I don't use conda, i think it's overly complex, and I don't know who controls the ta-lib recipes... 

But if you don't want to just install it the normal way (https://github.com/TA-Lib/ta-lib-python/issues/127#issuecomment-1902213252), maybe you need to do it the conda way, which i haven't tested but perhaps is just

```
$ conda install libta-lib
$ conda install ta-lib
```

**Comment by mrjbq7** [comment]
Did that work for you?

**Comment by mrjbq7** [comment]
Hi @jhvissotto did that work for you?

**Comment by jhvissotto** [comment]
"conda install conda-forge::libta-lib" Yes! 
"conda install conda-forge::ta-lib" did not work

![image](https://github.com/TA-Lib/ta-lib-python/assets/19745638/2634a927-3ad2-46df-ab57-1a57c74da1c8)

"import talib" continue not being resolved by VSCode interpreter. Anyway. I'm using panda_ta now. It's a practical solution. But I thank you for help
