### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by zobu1** [TA-Lib/ta-lib-python#638]
I am using fedora 37 and am attempting to install ta lib using pip. I have the underlying C library installed, so I'm not sure what the issue is, I would appreciate some help, thanks.

Building wheels for collected packages: ta-lib
  Building wheel for ta-lib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for ta-lib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [81 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/talib
      copying talib/stream.py -> build/lib.linux-x86_64-cpython-39/talib
      copying talib/deprecated.py -> build/lib.linux-x86_64-cpython-39/talib
      copying talib/abstract.py -> build/lib.linux-x86_64-cpython-39/talib
      copying talib/__init__.py -> build/lib.linux-x86_64-cpython-39/talib
      running build_ext
      building 'talib._ta_lib' extension
      creating build/temp.linux-x86_64-cpython-39
      creating build/temp.linux-x86_64-cpython-39/talib
      gcc -pthread -B /home/zobu/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/zobu/anaconda3/include -I/home/zobu/anaconda3/include -fPIC -O2 -isystem /home/zobu/anaconda3/include -fPIC -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/tmp/pip-build-env-ei8ix__x/normal/lib/python3.9/site-packages/numpy/core/include -I/home/zobu/anaconda3/include/python3.9 -c talib/_ta_lib.c -o build/temp.linux-x86_64-cpython-39/talib/_ta_lib.o
      In file included from /tmp/pip-build-env-ei8ix__x/normal/lib/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                       from /tmp/pip-build-env-ei8ix__x/normal/lib/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                       from /tmp/pip-build-env-ei8ix__x/normal/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                       from talib/_ta_lib.c:1092:
      /tmp/pip-build-env-ei8ix__x/normal/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
         17 | #warning "Using deprecated NumPy API, disable it with " \
            |  ^~~~~~~
      talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_348_ta_getFuncInfo’:
      talib/_ta_lib.c:51556:48: warning: passing argument 2 of ‘TA_GetFuncInfo’ from incompatible pointer type [-Wincompatible-pointer-types]
      51556 |   __pyx_v_retCode = TA_GetFuncInfo(__pyx_t_1, (&__pyx_v_info));
            |                                               ~^~~~~~~~~~~~~~
            |                                                |
            |                                                TA_FuncInfo **
      In file included from talib/_ta_lib.c:1084:
      /usr/include/ta-lib/ta_abstract.h:211:48: note: expected ‘const TA_FuncInfo **’ but argument is of type ‘TA_FuncInfo **’
        211 |                            const TA_FuncInfo **funcInfo );
            |                            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~
      talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_350_ta_getInputParameterInfo’:
      talib/_ta_lib.c:51832:71: warning: passing argument 3 of ‘TA_GetInputParameterInfo’ from incompatible pointer type [-Wincompatible-pointer-types]
      51832 |   __pyx_v_retCode = TA_GetInputParameterInfo(__pyx_t_1, __pyx_v_idx, (&__pyx_v_info));
            |                                                                      ~^~~~~~~~~~~~~~
            |                                                                       |
            |                                                                       TA_InputParameterInfo **
      /usr/include/ta-lib/ta_abstract.h:442:68: note: expected ‘const TA_InputParameterInfo **’ but argument is of type ‘TA_InputParameterInfo **’
        442 |                                      const TA_InputParameterInfo **info );
            |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
      talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_352_ta_getOptInputParameterInfo’:
      talib/_ta_lib.c:52084:74: warning: passing argument 3 of ‘TA_GetOptInputParameterInfo’ from incompatible pointer type [-Wincompatible-pointer-types]
      52084 |   __pyx_v_retCode = TA_GetOptInputParameterInfo(__pyx_t_1, __pyx_v_idx, (&__pyx_v_info));
            |                                                                         ~^~~~~~~~~~~~~~
            |                                                                          |
            |                                                                          TA_OptInputParameterInfo **
      /usr/include/ta-lib/ta_abstract.h:446:74: note: expected ‘const TA_OptInputParameterInfo **’ but argument is of type ‘TA_OptInputParameterInfo **’
        446 |                                         const TA_OptInputParameterInfo **info );
            |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
      talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_354_ta_getOutputParameterInfo’:
      talib/_ta_lib.c:52374:72: warning: passing argument 3 of ‘TA_GetOutputParameterInfo’ from incompatible pointer type [-Wincompatible-pointer-types]
      52374 |   __pyx_v_retCode = TA_GetOutputParameterInfo(__pyx_t_1, __pyx_v_idx, (&__pyx_v_info));
            |                                                                       ~^~~~~~~~~~~~~~
            |                                                                        |
            |                                                                        TA_OutputParameterInfo **
      /usr/include/ta-lib/ta_abstract.h:450:70: note: expected ‘const TA_OutputParameterInfo **’ but argument is of type ‘TA_OutputParameterInfo **’
        450 |                                       const TA_OutputParameterInfo **info );
            |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
      talib/_ta_lib.c: In function ‘__pyx_f_5talib_7_ta_lib___ta_getFuncHandle’:
      talib/_ta_lib.c:53011:126: warning: passing argument 2 of ‘TA_GetFuncHandle’ from incompatible pointer type [-Wincompatible-pointer-types]
      53011 |   __pyx_t_1 = __pyx_f_5talib_7_ta_lib__ta_check_success(__pyx_n_s_TA_GetFuncHandle, TA_GetFuncHandle(__pyx_v_function_name, (&__pyx_v_handle)), 0); if (unlikely(!__pyx_t_1)) __PYX_ERR(1, 772, __pyx_L1_error)
            |                                                                                                                             ~^~~~~~~~~~~~~~~~
            |                                                                                                                              |
            |                                                                                                                              TA_FuncHandle ** {aka unsigned int **}
      /usr/include/ta-lib/ta_abstract.h:155:52: note: expected ‘const TA_FuncHandle **’ {aka ‘const unsigned int **’} but argument is of type ‘TA_FuncHandle **’ {aka ‘unsigned int **’}
        155 |                              const TA_FuncHandle **handle );
            |                              ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
      gcc -pthread -B /home/zobu/anaconda3/compiler_compat -shared -Wl,-rpath,/home/zobu/anaconda3/lib -Wl,-rpath-link,/home/zobu/anaconda3/lib -L/home/zobu/anaconda3/lib -L/home/zobu/anaconda3/lib -Wl,-rpath,/home/zobu/anaconda3/lib -Wl,-rpath-link,/home/zobu/anaconda3/lib -L/home/zobu/anaconda3/lib build/temp.linux-x86_64-cpython-39/talib/_ta_lib.o -L/usr/lib -L/usr/local/lib -L/usr/lib64 -L/usr/local/lib64 -L/opt/lib -L/opt/local/lib -L/opt/homebrew/lib -L/opt/homebrew/opt/ta-lib/lib -Wl,--enable-new-dtags,-R/usr/lib -Wl,--enable-new-dtags,-R/usr/local/lib -Wl,--enable-new-dtags,-R/usr/lib64 -Wl,--enable-new-dtags,-R/usr/local/lib64 -Wl,--enable-new-dtags,-R/opt/lib -Wl,--enable-new-dtags,-R/opt/local/lib -Wl,--enable-new-dtags,-R/opt/homebrew/lib -Wl,--enable-new-dtags,-R/opt/homebrew/opt/ta-lib/lib -lta_lib -o build/lib.linux-x86_64-cpython-39/talib/_ta_lib.cpython-39-x86_64-linux-gnu.so
      /home/zobu/anaconda3/compiler_compat/ld: /lib64/libc.so.6: unknown type [0x13] section `.relr.dyn'
      /home/zobu/anaconda3/compiler_compat/ld: skipping incompatible /lib64/libc.so.6 when searching for /lib64/libc.so.6
      /home/zobu/anaconda3/compiler_compat/ld: cannot find /lib64/libc.so.6
      /home/zobu/anaconda3/compiler_compat/ld: /lib64/libc.so.6: unknown type [0x13] section `.relr.dyn'
      /home/zobu/anaconda3/compiler_compat/ld: skipping incompatible /lib64/libc.so.6 when searching for /lib64/libc.so.6
      /home/zobu/anaconda3/compiler_compat/ld: /lib64/ld-linux-x86-64.so.2: unknown type [0x13] section `.relr.dyn'
      /home/zobu/anaconda3/compiler_compat/ld: skipping incompatible /lib64/ld-linux-x86-64.so.2 when searching for /lib64/ld-linux-x86-64.so.2
      /home/zobu/anaconda3/compiler_compat/ld: cannot find /lib64/ld-linux-x86-64.so.2
      /home/zobu/anaconda3/compiler_compat/ld: /lib64/ld-linux-x86-64.so.2: unknown type [0x13] section `.relr.dyn'
      /home/zobu/anaconda3/compiler_compat/ld: skipping incompatible /lib64/ld-linux-x86-64.so.2 when searching for /lib64/ld-linux-x86-64.so.2
      collect2: error: ld returned 1 exit status
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ta-lib
Failed to build ta-lib
ERROR: Could not build wheels for ta-lib, which is required to install pyproject.toml-based projects

**Comment by mrjbq7** [comment]
That error doesn't look like an issue with ta-lib, it looks like some problem with your compiler installation...

**Comment by mrjbq7** [comment]
Perhaps you can search for that error message, for example:

https://bbs.archlinux.org/viewtopic.php?id=278679

**Comment by mrjbq7** [comment]
If i had to guess, it's because somehow you tried to install a local compiler in ``/home/zobu/anaconda3/compiler_compat/ld`` instead of using the one installed in fedora...

**Comment by zobu1** [comment]
The local compiler from anaconda3 was the issue. Thanks so much for your help!

**Comment by jmo5k02** [comment]
How were you able to fix the problem?

**Comment by mupalvan** [comment]
![Screenshot 2024-02-19 224830](https://github.com/TA-Lib/ta-lib-python/assets/77997241/ef000447-6ad3-4354-a69e-e54a2ab298b9)
I have this problem on Windows

**Comment by mrjbq7** [comment]
Do you see that warning “can’t find the ta-lib library”?Look at the README and make sure you have the ta-lib library installed. On Feb 20, 2024, at 5:07 AM, mupalvan ***@***.***> wrote:﻿
Screenshot.2024-02-19.224830.png (view on web)
I have this problem on Windows
