### ISSUE TITLE
install problem - outdated config.guess and config.sub

### ISSUE THREAD

**Issue by kakulukia** [TA-Lib/ta-lib-python#641]
I tried to install ta lib on my Raspberry which did not work:

checking build system type... ./config.guess: unable to guess system type

This script, last modified 2006-07-02, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess
and
  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub

But visiting the urls mentioned gives a somewhat 15 years more recent version of those files .. and it worked!

I could not find those files in the repo itself, otherwise i would have prepared a PR .. please update the build files!

**Comment by mrjbq7** [comment]
Are you talking about the C library?

If so, we should track that in the ta-lib/ta-lib repo.

**Comment by kakulukia** [comment]
Oh yes, that step was about installing the lib via the downloaded tar.
