### ISSUE TITLE
Pip Installation issue in Windows and Mac OS

### ISSUE THREAD

**Issue by Pruthvi-Raj-S** [TA-Lib/ta-lib-python#650]
## PIP installation issue

- When tried to install TA Lib with the help of pip in both windows and Mac OS. Using the below command.
`pip install TA-Lib`

The Terminal Snippet for the same is attached below:

Collecting TA-Lib
  Using cached TA-Lib-0.4.28.tar.gz (357 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from TA-Lib) (1.26.4)
Building wheels for collected packages: TA-Lib
  Building wheel for TA-Lib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for TA-Lib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      <string>:77: UserWarning: Cannot find ta-lib library, installation may fail.
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-312
      creating build/lib.macosx-10.9-universal2-cpython-312/talib
      copying talib/abstract.py -> build/lib.macosx-10.9-universal2-cpython-312/talib
      copying talib/deprecated.py -> build/lib.macosx-10.9-universal2-cpython-312/talib
      copying talib/__init__.py -> build/lib.macosx-10.9-universal2-cpython-312/talib
      copying talib/stream.py -> build/lib.macosx-10.9-universal2-cpython-312/talib
      running build_ext
      building 'talib._ta_lib' extension
      creating build/temp.macosx-10.9-universal2-cpython-312
      creating build/temp.macosx-10.9-universal2-cpython-312/talib
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -arch arm64 -arch x86_64 -g -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/private/var/folders/rd/fdkmtc1n69sdp88jt8qw72v00000gn/T/pip-build-env-8jbitcc0/normal/lib/python3.12/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c talib/_ta_lib.c -o build/temp.macosx-10.9-universal2-cpython-312/talib/_ta_lib.o
      talib/_ta_lib.c:1082:10: fatal error: 'ta-lib/ta_defs.h' file not found
      #include "ta-lib/ta_defs.h"
               ^~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for TA-Lib
Failed to build TA-Lib
ERROR: Could not build wheels for TA-Lib, which is required to install pyproject.toml-based projects

**Comment by mrjbq7** [comment]
Guys read the README :77: UserWarning: Cannot find ta-lib library, installation may fail.On May 12, 2024, at 12:28 AM, Pruthvi Raj S ***@***.***> wrote:﻿
PIP installation issue

When tried to install TA Lib with the help of pip in both windows and Mac OS. Using the below command.
pip install TA-Lib

The Terminal Snippet for the same is attached below:
Collecting TA-Lib
Using cached TA-Lib-0.4.28.tar.gz (357 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... done
Installing backend dependencies ... done
Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from TA-Lib) (1.26.4)
Building wheels for collected packages: TA-Lib
Building wheel for TA-Lib (pyproject.toml) ... error
error: subprocess-exited-with-error
× Building wheel for TA-Lib (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [21 lines of output]
:77: UserWarning: Cannot find ta-lib library, installation may fail.
running bdist_wheel
running build
running build_py
creating build
creating build/lib.macosx-10.9-universal2-cpython-312
creating build/lib.macosx-10.9-universal2-cpython-312/talib
copying talib/abstract.py -> build/lib.macosx-10.9-universal2-cpython-312/talib
copying talib/deprecated.py -> build/lib.macosx-10.9-universal2-cpython-312/talib
copying talib/init.py -> build/lib.macosx-10.9-universal2-cpython-312/talib
copying talib/stream.py -> build/lib.macosx-10.9-universal2-cpython-312/talib
running build_ext
building 'talib._ta_lib' extension
creating build/temp.macosx-10.9-universal2-cpython-312
creating build/temp.macosx-10.9-universal2-cpython-312/talib
clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -arch arm64 -arch x86_64 -g -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/private/var/folders/rd/fdkmtc1n69sdp88jt8qw72v00000gn/T/pip-build-env-8jbitcc0/normal/lib/python3.12/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c talib/_ta_lib.c -o build/temp.macosx-10.9-universal2-cpython-312/talib/_ta_lib.o
talib/_ta_lib.c:1082:10: fatal error: 'ta-lib/ta_defs.h' file not found
#include "ta-lib/ta_defs.h"
^~~~~~~~~~~~~~~~~~
1 error generated.
error: command '/usr/bin/clang' failed with exit code 1
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for TA-Lib
Failed to build TA-Lib
ERROR: Could not build wheels for TA-Lib, which is required to install pyproject.toml-based projects
