### ISSUE TITLE
ERROR: Failed building wheel for TA-Lib

### ISSUE THREAD

**Issue by akitxu** [TA-Lib/ta-lib-python#651]
Dear all
When I try to install Ta-lib using the terminal on a Linux Mint 21.3 OS, LinuxMint 21.3,  in a virtual environment with Python 3.8, I get the following error:
"(py38) enri@enri-260-p100ns:~$ python -m pip install TA-Lib
Collecting TA-Lib
  Using cached TA-Lib-0.4.28.tar.gz (357 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in ./anaconda3/envs/py38/lib/python3.8/site-packages (from TA-Lib) (1.24.4)
Building wheels for collected packages: TA-Lib
  Building wheel for TA-Lib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for TA-Lib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/talib
      copying talib/stream.py -> build/lib.linux-x86_64-cpython-38/talib
      copying talib/__init__.py -> build/lib.linux-x86_64-cpython-38/talib
      copying talib/abstract.py -> build/lib.linux-x86_64-cpython-38/talib
      copying talib/deprecated.py -> build/lib.linux-x86_64-cpython-38/talib
      running build_ext
      building 'talib._ta_lib' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/talib
      gcc -pthread -B /home/enri/anaconda3/envs/py38/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/tmp/pip-build-env-p4z6prv8/normal/lib/python3.8/site-packages/numpy/core/include -I/home/enri/anaconda3/envs/py38/include/python3.8 -c talib/_ta_lib.c -o build/temp.linux-x86_64-cpython-38/talib/_ta_lib.o
      In file included from /usr/lib/gcc/x86_64-linux-gnu/11/include/syslimits.h:7,
                       from /usr/lib/gcc/x86_64-linux-gnu/11/include/limits.h:34,
                       from /home/enri/anaconda3/envs/py38/include/python3.8/Python.h:11,
                       from talib/_ta_lib.c:16:
      /usr/lib/gcc/x86_64-linux-gnu/11/include/limits.h:203:15: fatal error: limits.h: No existe el archivo o el directorio
        203 | #include_next <limits.h>                /* recurse down to the real one */
            |               ^~~~~~~~~~
      compilation terminated.
      <string>:77: UserWarning: Cannot find ta-lib library, installation may fail.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for TA-Lib
Failed to build TA-Lib
ERROR: Could not build wheels for TA-Lib, which is required to install pyproject.toml-based projects
"
How can I solve this problem? Any help would be appreciated.

**Comment by mrjbq7** [comment]
Please read the README and install the TA-Lib C library that this requires.

```
:77: UserWarning: Cannot find ta-lib library, installation may fail.
error: command '/usr/bin/gcc' failed with exit code 1
```

**Comment by mrjbq7** [comment]
https://github.com/TA-Lib/ta-lib-python?tab=readme-ov-file#linux
