### ISSUE TITLE
ValueError: Cannot import module talib. Check if talib is installed correctly

### ISSUE THREAD

**Issue by tom634** [TA-Lib/ta-lib-python#667]
Why can't I use talib?
I installed it via:
$ python -m pip install TA-Lib 
no success:
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for TA-Lib
Failed to build TA-Lib
ERROR: Could not build wheels for TA-Lib, which is required to install pyproject.toml-based projects

then via native tools prompt winth nmake:
![obraz](https://github.com/user-attachments/assets/fe142370-830c-456b-a33c-9acc27a9b433)
also no success.
What else can I try?

**Comment by mrjbq7** [comment]
Install the underlying TA-Lib C library (https://github.com/ta-lib/ta-lib-python?tab=readme-ov-file#windows) and then install this library (https://github.com/ta-lib/ta-lib-python?tab=readme-ov-file#installation).
