### ISSUE TITLE
Some tests are unable to pass with TA-LIB 0.6.0

### ISSUE THREAD

**Issue by YadavGulshan** [TA-Lib/ta-lib-python#668]
Hi, I'm using the 0.6.0 release of TA-LIB and while testing this project, I came across an issue with the RSI indicator and EMA indicator.

```
result = func.RSI(a, 10)
assert_array_equal(result, [np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,0,0,0,0,0,0,0,0,0,0])
```
For the above indicator, the result I got is,
```
[      nan,       nan,       nan,       nan,       nan,       nan,
       nan,       nan,       nan,       nan, 33.333333, 51.351351,
       39.491917, 51.84807 , 42.259538, 52.101824, 52.101824, 43.043665,
       43.043665, 43.043665]
```

I checked the code of TA-LIB 0.4.0, the code is identical but still I'm getting this as a result, but when I use the TA-LIB 0.4.0, the result is all zero which is correct.

---
Another issue I'm facing is with the `unstable period` test,
```py
def test_unstable_period():
    a = np.arange(10, dtype=float)
    r = func.EMA(a, 3)
    assert_array_equal(r, [np.nan, np.nan, 1, 2, 3, 4, 5, 6, 7, 8])
    talib.set_unstable_period('EMA', 5)
    r = func.EMA(a, 3)
    assert_array_equal(r, [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, 6, 7, 8]) # Issue here.
    talib.set_unstable_period('EMA', 0)
```

Result: `[nan, nan,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.]`

---
Can you guide me a little on how to fix these issues?

And I also needed your help in knowing how to generate documentation for new indicators, I tried looking for the relevant code in both the Library and `ta-lib-python`. But I couldn't find any, can you please guide me here too?

Thanks 😄

**Comment by mrjbq7** [comment]
What is the 0.6.0 release?

The last official release was 0.4.0?

**Comment by YadavGulshan** [comment]
I'm not sure why but my project returns `0.6.0` as the version of TA-LIB. I do remember that I cloned the official repo of TA-LIB into my [repo](https://github.com/yadavgulshan/ta-lib).

---
let's ignore that for a sec, I wanted to know how I can generate `info` for my custom indicator.


`generate_func.py`
```python
    try:
        func_info = abstract.Function(shortname).info
        defaults, documentation = abstract._get_defaults_and_docs(func_info)
    except Exception as e:
        print('Error: %s' % e, file=sys.stderr)
        func_info, defaults, documentation = {}, {}, ""
 ```
 
In my other project, I'm using this info property to properly push data into the indicator. So I need this property to work.

---
Give me a gist of it, and I'll have a look, I won't bug you much about this.

**Comment by mrjbq7** [comment]
I don’t mind at all. 

One thing is the ta-lib-rt project is the one you look to have cloned and is kind of an unofficial fork with some cool experiments in it.  Not sure if everything is working because I haven’t looked at it much recently. 

Also, the abstract interface has a bunch of data blocks that define it for each indicator. 

https://github.com/TA-Lib/ta-lib/tree/main/src/ta_abstract/tables

**Comment by mrjbq7** [comment]
Regarding the epsilon value, people have been making that change to support prices that are quite small, but I’ve wondered if any issues would crop up. Seems like it maybe needs to be slightly larger or to understand more the implications of what threshold to use.

**Comment by mrjbq7** [comment]
You might also find these discussions useful:

https://github.com/TA-Lib/ta-lib-python/issues/255

https://github.com/TA-Lib/ta-lib-python/issues/515

https://github.com/TA-Lib/ta-lib-python/issues/524

A fair amount of the discussion includes the author of the ta-lib-rt fork. I’d love to get that code upstreamed if/when it’s stable enough.

**Comment by YadavGulshan** [comment]
This https://github.com/YadavGulshan/ta-lib/tree/main/ta-lib-rt/ta-lib part of my project is a clone of official `TA-LIB`, I was facing some issues with not having Java files while compiling the official project thus I had to use `ta-lib-rt`. 

Let's take an example of this indicator https://github.com/YadavGulshan/ta-lib/blob/main/ta-lib-rt/ta-lib/src/ta_abstract/tables/table_x.c

`XBAR` am I missing something in my implementation?

Or is something wrong with the cmake file?

install manifest:
```
/usr/local/include/ta-lib/ta_abstract.h
/usr/local/include/ta-lib/ta_common.h
/usr/local/include/ta-lib/ta_defs.h
/usr/local/include/ta-lib/ta_func.h
/usr/local/include/ta-lib/ta_libc.h
/usr/local/lib/libta_lib.0.8.1-alpha.dylib
/usr/local/lib/libta_lib.0.dylib
/usr/local/lib/libta_lib.dylib
/usr/local/lib/libta_lib.a
```

code from `/usr/local/include/ta-lib/ta_func.h` for XBAR,
```c


/*
 * TA_AVGXBAR - Avg X-Bar: Avg High, Low, and Volume lines for the last N periods
 * 
 * Input  = High, Low, Volume
 * Output = double, double, double
 * 
 * Optional Parameters
 * -------------------
 * optInTimePeriod:(From 1 to 100000)
 *    Number of period
 * 
 * 
 */
TA_LIB_API TA_RetCode TA_AVGXBAR( int    startIdx,
                                  int    endIdx,
                                             const double inHigh[],
                                             const double inLow[],
                                             const double inVolume[],
                                             int           optInTimePeriod, /* From 1 to 100000 */
                                             int          *outBegIdx,
                                             int          *outNBElement,
                                             double        outHigh[],
                                             double        outLow[],
                                             double        outVolume[] );

TA_LIB_API TA_RetCode TA_S_AVGXBAR( int    startIdx,
                                    int    endIdx,
                                               const float  inHigh[],
                                               const float  inLow[],
                                               const float  inVolume[],
                                               int           optInTimePeriod, /* From 1 to 100000 */
                                               int          *outBegIdx,
                                               int          *outNBElement,
                                               double        outHigh[],
                                               double        outLow[],
                                               double        outVolume[] );

TA_LIB_API int TA_AVGXBAR_Lookback( int           optInTimePeriod );  /* From 1 to 100000 */
```

**Comment by YadavGulshan** [comment]
Thanks, I'll look into the discussions.

**Comment by mrjbq7** [comment]
Silly question but the abstract block for XBAR should that match the AVGXBAR indicator?

**Comment by YadavGulshan** [comment]
No, XBAR for last N bar high, low, and vol. AvgXbar for avg of HLV.

**Comment by YadavGulshan** [comment]
I also found another issue, after I generated `_func.pxi` and `_stream.pxi`. And when I execute `make compile` I'm getting this error,

```

Error compiling Cython file:
------------------------------------------------------------
...
    low = check_array(low)
    low_data = <double*>low.data
    length = check_length2(high, low)
    outhigh = NaN
    outlow = NaN
    retCode = lib.TA_XBAR( <int>(length) - 1 , <int>(length) - 1 , high_data , low_data , timeperiod , &outbegidx , &outnbelement , &outhigh , &outlow )
                 ^
------------------------------------------------------------

talib/_stream.pxi:5541:17: cimported module has no attribute 'TA_XBAR'

```

What do you think is why I am getting this error?

**Comment by mrjbq7** [comment]
All the external symbols are defined here:

https://github.com/TA-Lib/ta-lib-python/blob/master/talib/_ta_lib.pxd

**Comment by YadavGulshan** [comment]
Thanks! I'll manually add the indicators or look for ways I can generate this file. But about the `abstract.Function(shortname).info`, how can I make TA-LIB to include function info?

**Comment by mrjbq7** [comment]
I think the abstract/table files are sufficient, but perhaps ripgrep for
another indicator like RSI and see what else might be referenced in the
TA-LIB side.

**Comment by mrjbq7** [comment]
Did that help you?

**Comment by YadavGulshan** [comment]
No, I tried comparing my indicators with others, but they look correct to me 😞 

I'm not sure what's missing..

**Comment by YadavGulshan** [comment]
```
{'name': 'XBAR', 'group': 'Overlap Studies', 'display_name': 'X-Bar: High and Low lines for the last N periods', 'function_flags': None, 'input_names': OrderedDict([('prices', ['high', 'low'])]), 'parameters': OrderedDict([('timeperiod', 1)]), 'output_flags': OrderedDict([('xhigh', ['Line']), ('xlow', ['Line'])]), 'output_names': ['xhigh', 'xlow']}

```

HELL YEAH!!! Done.

Thanks
