### ISSUE TITLE
Hanging process:  Building wheel for Ta-Lib (pyproject.toml) ... \

### ISSUE THREAD

**Issue by bizso09** [TA-Lib/ta-lib-python#670]
Installing it for Python 3.12, pip3 install --break-system-packages Ta-Lib, process is hanging.

**Comment by mrjbq7** [comment]
Could you give more info?On Aug 4, 2024, at 9:30 PM, bizso09 ***@***.***> wrote:﻿
Installing it for Python 3.12, pip3 install --break-system-packages Ta-Lib, process is hanging.

**Comment by bizso09** [comment]
Building wheel for Ta-Lib (pyproject.toml) ... \^canceled
^C^CTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 420, in run
    _, build_failures = build(
                        ^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/wheel_builder.py", line 319, in build
    wheel_file = _build_one(
                 ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/wheel_builder.py", line 193, in _build_one
    wheel_path = _build_one_inside_env(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/wheel_builder.py", line 233, in _build_one_inside_env
    wheel_path = build_wheel_pep517(
                 ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/build/wheel.py", line 30, in build_wheel_pep517
    wheel_name = backend.build_wheel(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 718, in build_wheel
    return super().build_wheel(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_impl.py", line 209, in build_wheel
    return self._call_hook('build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/subprocess.py", line 252, in runner
    call_subprocess(
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/subprocess.py", line 166, in call_subprocess
    line: str = proc.stdout.readline()
                ^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

It seems like it's waiting from some process. How long is building the wheel supposed to take normally?

**Comment by bizso09** [comment]
sudo pip3 install --break-system-packages Ta-Lib --verbose
Using pip 24.0 from /usr/lib/python3/dist-packages/pip (python 3.12)
Collecting Ta-Lib
  Using cached TA-Lib-0.4.32.tar.gz (368 kB)
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=51.0.0
    Using cached setuptools-72.1.0-py3-none-any.whl.metadata (6.6 kB)
  Collecting wheel
    Using cached wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
  Collecting numpy<2.0.0
    Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
  Using cached setuptools-72.1.0-py3-none-any.whl (2.3 MB)
  Using cached wheel-0.44.0-py3-none-any.whl (67 kB)
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
  Installing collected packages: wheel, setuptools, numpy
  Successfully installed numpy-1.26.4 setuptools-72.1.0 wheel-0.44.0
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-nrh6pmfq/TA_Lib.egg-info
  writing /tmp/pip-modern-metadata-nrh6pmfq/TA_Lib.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-nrh6pmfq/TA_Lib.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-modern-metadata-nrh6pmfq/TA_Lib.egg-info/requires.txt
  writing top-level names to /tmp/pip-modern-metadata-nrh6pmfq/TA_Lib.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-nrh6pmfq/TA_Lib.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-modern-metadata-nrh6pmfq/TA_Lib.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  adding license file 'AUTHORS'
  writing manifest file '/tmp/pip-modern-metadata-nrh6pmfq/TA_Lib.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-nrh6pmfq/TA_Lib-0.4.32.dist-info'
  Preparing metadata (pyproject.toml) ... done
  Link requires a different Python (3.12.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/3a/be/650f9c091ef71cb01d735775d554e068752d3ff63d7943b26316dc401749/numpy-1.21.2.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
  Link requires a different Python (3.12.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/5f/d6/ad58ded26556eaeaa8c971e08b6466f17c4ac4d786cd3d800e26ce59cc01/numpy-1.21.3.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
  Link requires a different Python (3.12.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/fb/48/b0708ebd7718a8933f0d3937513ef8ef2f4f04529f1f66ca86d873043921/numpy-1.21.4.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
  Link requires a different Python (3.12.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/c2/a8/a924a09492bdfee8c2ec3094d0a13f2799800b4fdc9c890738aeeb12c72e/numpy-1.21.5.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
  Link requires a different Python (3.12.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/45/b7/de7b8e67f2232c26af57c205aaad29fe17754f793404f59c8a730c7a191a/numpy-1.21.6.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
Collecting numpy (from Ta-Lib)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/2c/f3/61eeef119beb37decb58e7cb29940f19a1464b8608f2cab8a8616aba75fd/numpy-2.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached numpy-2.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Using cached numpy-2.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.2 MB)
Building wheels for collected packages: Ta-Lib
  Running command Building wheel for Ta-Lib (pyproject.toml)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-cpython-312
  creating build/lib.linux-x86_64-cpython-312/talib
  copying talib/deprecated.py -> build/lib.linux-x86_64-cpython-312/talib
  copying talib/__init__.py -> build/lib.linux-x86_64-cpython-312/talib
  copying talib/stream.py -> build/lib.linux-x86_64-cpython-312/talib
  copying talib/abstract.py -> build/lib.linux-x86_64-cpython-312/talib
  running build_ext
  building 'talib._ta_lib' extension
  creating build/temp.linux-x86_64-cpython-312
  creating build/temp.linux-x86_64-cpython-312/talib
  x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -fPIC -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/tmp/pip-build-env-u8c21bx6/overlay/local/lib/python3.12/dist-packages/numpy/core/include -I/usr/include/python3.12 -c talib/_ta_lib.c -o build/temp.linux-x86_64-cpython-312/talib/_ta_lib.o
  In file included from /tmp/pip-build-env-u8c21bx6/overlay/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                   from /tmp/pip-build-env-u8c21bx6/overlay/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /tmp/pip-build-env-u8c21bx6/overlay/local/lib/python3.12/dist-packages/numpy/core/include/numpy/arrayobject.h:5,
                   from talib/_ta_lib.c:1235:
  /tmp/pip-build-env-u8c21bx6/overlay/local/lib/python3.12/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     17 | #warning "Using deprecated NumPy API, disable it with " \
        |  ^~~~~~~

**Comment by bizso09** [comment]
Ok, finished after 1 hour. Running on some AWS EC2 instance.

**Comment by mrjbq7** [comment]
Wow! That’s unusual
