### ISSUE TITLE
I have successfully added ta-lib library to my VirtualEnv but I am getting error while importing it.

### ISSUE THREAD

**Issue by AdityaTiwari1999** [TA-Lib/ta-lib-python#674]
Hi Team, First of all thanks for creating this library. 
 I am getting below error while trying to import it.
![image](https://github.com/user-attachments/assets/f102976e-059f-4c18-8161-d30b62082ef1)

Can you please help me with this?

**Comment by mrjbq7** [comment]
Probably related to trying to use numpy>=2.  Recommend using numpy<2.

I think we are waiting for cython compatibility upstream.

**Comment by rbosneag** [comment]
Thanks for the answer, @mrjbq7! Any good news on this numpy2 issue after your last Cython upgrade?

I have the same problem and I guess everyone else lately, if you take a look at the issues list there's plenty of them. 
Meanwhile we will use the "numpy < 2" solution...

**Comment by mrjbq7** [comment]
Not at the moment, supposedly it could work if you make your own cython C files against numpy2, need to investigate more.

**Comment by looker01202** [comment]
I had the same problem and tried various versions of numpy.  Many 1.x.x failed with same problem but v1.26.4 worked in my environment.

**Comment by mrjbq7** [comment]
Released ta-lib 0.5.0 with numpy 2.0 support.

Also released ta-lib 0.4.33 with numpy<2.0 support.
