### ISSUE TITLE
Additional Files Needed for TA-Lib Dockerfile Setup

### ISSUE THREAD

**Issue by BouarfaMahi** [TA-Lib/ta-lib-python#677]
hey,

I would like to use the TA-Lib Dockerfile as a container within a Docker Compose setup. Could you please let me know which additional relevant files from the TA-Lib directory I would need to include to complete the setup?

thank you

**Comment by mrjbq7** [comment]
Like this dockerfile?

https://github.com/TA-Lib/ta-lib-python/blob/master/Dockerfile

I would assume instead it would download the C library and install the python ta-lib using pip…

**Comment by BouarfaMahi** [comment]
Yes i have use it in a docker compose and the docker stack doest not complete with this error message:

=> ERROR [talib builder 6/7] RUN python -m pip install -e .     &&  1.6s

 > [talib builder 6/7] RUN python -m pip install -e .     && python -c 'import numpy, talib; close = numpy.random.random(100); output = talib.SMA(close); print(output)'     && python -m pip wheel --wheel-dir wheels .:
1.348 Obtaining file:///src/ta-lib-python
1.349 ERROR: file:///src/ta-lib-python does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
1.521 
1.521 [notice] A new release of pip is available: 23.0.1 -> 24.0
1.521 [notice] To update, run: pip install --upgrade pip

failed to solve: process "/bin/sh -c python -m pip install -e .     && python -c 'import numpy, talib; close = numpy.random.random(100); output = talib.SMA(close); print(output)'     && python -m pip wheel --wheel-dir wheels ." did not complete successfully: exit code: 1

**Comment by mrjbq7** [comment]
Right, you probably want it to not use that src directory unless you are trying to bundle the git repo, and just have a pip install ta-lib step.

**Comment by BouarfaMahi** [comment]
After updating my Docker Compose with:


`
  talib:
    build:
      context: ./talib
      dockerfile: Dockerfile
    ports: []
    volumes:
      - ./data:/app/data
    environment:
      - DB_HOST=questdb
      - DB_PORT=9000
    depends_on:
      - questdb

`
I created a talib directory and cloned the ta-lib-python repository. Now the Docker stack completes successfully without any issues.

Thank you
