### ISSUE TITLE
ModuleNotFoundError: No module named 'TA_Lib'

### ISSUE THREAD

**Issue by AufiTM62M** [TA-Lib/ta-lib-python#680]
Hi guys, i have a problem. I installed Talib on Miniconda and Windows. Everything was fine until i run into a problem. When i use 'import talib as ta'. When i do this this appears 'ModuleNotFoundError: No module named 'TA_Lib''. I think the problem appears because of the difference in the names, and i cant use TA-Lib couse u cant use '-' in python. What should i do? 
![Zrzut ekranu 2024-10-24 204211](https://github.com/user-attachments/assets/a4fed970-7354-4637-b22a-6dc24e0ecefe)

**Comment by mrjbq7** [comment]
The module name is “talib”

**Comment by AufiTM62M** [comment]
> The module name is “talib”

Yeah i know i tried talib, TA-Lib, ta_lib and it's still the same problem

**Comment by mrjbq7** [comment]
Well then it’s not installed properly. 

Check the installation section of the README, particularly the dependencies, to make sure you have the underlying C library this depends upon. 

https://github.com/ta-lib/ta-lib-python?tab=readme-ov-file#installation
