### ISSUE TITLE
https://github.com/TA-Lib/ta-lib/releases v0.6.1 publish,When will it be adapted?

### ISSUE THREAD

**Issue by hyq1860** [TA-Lib/ta-lib-python#689]
https://github.com/TA-Lib/ta-lib/releases v0.6.1 publish,When will it be adapted?  Thank you very much

**Comment by mrjbq7** [comment]
Probably sometime in the next week or two. On Dec 24, 2024, at 6:06 PM, hyq1860 ***@***.***> wrote:﻿
https://github.com/TA-Lib/ta-lib/releases v0.6.1 publish,When will it be adapted?  Thank you very much

**Comment by mrjbq7** [comment]
Can you try the newly released ta-lib-python 0.5.2, it should look for both library names.
