### ISSUE TITLE
unable to import  talib with common error on python cygwin

### ISSUE THREAD

**Issue by ashgen** [TA-Lib/ta-lib-python#97]
> > import talib
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> >   File "talib/**init**.py", line 4, in <module>
> >     from . import common
> > ImportError: cannot import name common

Kindly help.

**Comment by mrjbq7** [comment]
Did you re-run ``setup.py``?

It ships with both the ``.pyx`` cython files and the generated ``.c`` files which are compiled into the ``abstract.so``, ``common.so``, and ``func.so`` modules.

**Comment by mrjbq7** [comment]
Do you have a ``talib/common.so`` file?

**Comment by ashgen** [comment]
Ya I rerun setup.py. as I observed the in setup.py if cython doesn't get .c
file it runs pyx though the issue remains the same.

**Comment by ashgen** [comment]
Nope I don't have the common.so file but have the pyd and pyx file for the
same.

**Comment by mrjbq7** [comment]
So, on Windows, the ``libta_lib`` include paths are different, so the ``common.c`` file has this declaration at the top:

```
#if defined(WIN32) || defined(MS_WINDOWS)
#include "ta_libc.h"
#else
#include "ta-lib/ta_defs.h"
#include "ta-lib/ta_common.h"
#include "ta-lib/ta_abstract.h"
#include "ta-lib/ta_func.h"
#endif
```

I haven't figured out how to support Windows without editing the C files after they are generated.  Perhaps if your cython build regenerates them for some reason the includes are messed up.  Can you see if that is the problem?

**Comment by mrjbq7** [comment]
That include is at the top of all 3 modules: ``common.c``, ``abstract.c``, and ``func.c``.

**Comment by mrjbq7** [comment]
One idea I had was to always include ``ta_libc.h`` on all platforms rather than the ``ifdef`` which would be more robust than me editing the C files before I commit them when they are changed.

**Comment by ashgen** [comment]
I do think this might be an issue . looking into it

**Comment by mrjbq7** [comment]
If the file is "buggy on Windows", it will only have this (you can search for it):

```C
#include "ta-lib/ta_defs.h"
#include "ta-lib/ta_common.h"
#include "ta-lib/ta_abstract.h"
#include "ta-lib/ta_func.h"
```

**Comment by ashgen** [comment]
Take the world's best courses, online. Coursera envisions a world where 
anyone, anywhere can transform their life by accessing the world’s best 
learning experience.
[Ready to learn something new?]
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLl94V3dQXzduRWVXVzloTDYwci1hS1EiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDYzNDliMzNiZjNhNTAxZmYwMzQzOGZjZjczODVlMDgzYzI1M2E0OGU2YWNhOTk5MmNmMDAwMDAwMDExMmEzZGJjZTkyYTE2OWNlMDc3M2Q5MWZAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uX3hXd1BfN25FZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.OhEf2jRr3sbECmBtoLG9UWhi5244kCJk638wBqgDE0U> 	
My Courses
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLl94V3dQXzduRWVXVzloTDYwci1hS1EiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDYzNDliMzNiZjNhNTAxZmYwMzQzOGZjZjczODVlMDgzYzI1M2E0OGU2YWNhOTk5MmNmMDAwMDAwMDExMmEzZGJjZTkyYTE2OWNlMDc3M2Q5MWZAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uX3hXd1BfN25FZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.OhEf2jRr3sbECmBtoLG9UWhi5244kCJk638wBqgDE0U> 
Course Catalog
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvY291cnNlcz91dG1fbWVkaXVtPWVtYWlsJnV0bV9zb3VyY2U9aW52aXRhdGlvbnMmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5feFd3UF83bkVlV1c5aEw2MHItYUtRIiwidHJhY2tpbmciOnsidXNlcklkIjotMSwidXNlckVtYWlsIjoicmVwbHkrMDA2MzQ5YjMzYmYzYTUwMWZmMDM0MzhmY2Y3Mzg1ZTA4M2MyNTNhNDhlNmFjYTk5OTJjZjAwMDAwMDAxMTJhM2RiY2U5MmExNjljZTA3NzNkOTFmQHJlcGx5LmdpdGh1Yi5jb20iLCJub3RpZmljYXRpb25UeXBlIjoiZ3Jvd3RoLmludml0YXRpb24iLCJjYW1wYWlnbklkIjoibm90aWZpY2F0aW9ucy5hdXRvLl94V3dQXzduRWVXVzloTDYwci1hS1EifX0sInVzZXJJZCI6LTF9.NC6aTQs6ozzmTqQqABh4-DpCJaw3sMHLnOsuuyrj1AI>


ashish sachan thinks you'll love learning on Coursera

We envision a world where anyone, anywhere can transform their life by 
accessing the world’s best learning experience. We offer hundreds open 
online courses, in dozens of subject areas, all from top universities and 
institutions.

Course topics range from business and management, to computer science, to 
medicine, music, education, and more.

Millions of our learners have advanced their careers, discovered new 
passions, and built lasting friendships through their Coursera courses. We 
hope you'll join us in learning without limits!

The Coursera Team

Explore Coursera
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvb25ib2FyZGluZy8_dG9rZW49NWM0YjEzMTYxYjI3Y2QzM2Q3Njg1NmM0ZDM5NTg1NDQmZW1haWw9cmVwbHkrMDA2MzQ5YjMzYmYzYTUwMWZmMDM0MzhmY2Y3Mzg1ZTA4M2MyNTNhNDhlNmFjYTk5OTJjZjAwMDAwMDAxMTJhM2RiY2U5MmExNjljZTA3NzNkOTFmQHJlcGx5LmdpdGh1Yi5jb20mbmFtZT1tcmpicTcvdGEtbGliP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLl94V3dQXzduRWVXVzloTDYwci1hS1EiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDYzNDliMzNiZjNhNTAxZmYwMzQzOGZjZjczODVlMDgzYzI1M2E0OGU2YWNhOTk5MmNmMDAwMDAwMDExMmEzZGJjZTkyYTE2OWNlMDc3M2Q5MWZAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uX3hXd1BfN25FZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.BkCsgo4GoUO-KCP8driU7KAVYWqLK_LUyf-t38FqgHo>
Download our App:  iOS
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2l0dW5lcy5hcHBsZS5jb20vYXBwL2FwcGxlLXN0b3JlL2lkNzM2NTM1OTYxP2N0PU1vYmlsZSUyMFByb21vJTIwRW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZtdD04JnB0PTIzMzQxNTAmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5feFd3UF83bkVlV1c5aEw2MHItYUtRJnV0bV9tZWRpdW09ZW1haWwiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDYzNDliMzNiZjNhNTAxZmYwMzQzOGZjZjczODVlMDgzYzI1M2E0OGU2YWNhOTk5MmNmMDAwMDAwMDExMmEzZGJjZTkyYTE2OWNlMDc3M2Q5MWZAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uX3hXd1BfN25FZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.xELmTSRTVILbJEQBSo6oCXAnEWzfPnfgQU_2uhaKdUA> 
  |  Android
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3BsYXkuZ29vZ2xlLmNvbS9zdG9yZS9hcHBzL2RldGFpbHM_aWQ9b3JnLmNvdXJzZXJhLmFuZHJvaWQmdXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uX3hXd1BfN25FZVdXOWhMNjByLWFLUSIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwNjM0OWIzM2JmM2E1MDFmZjAzNDM4ZmNmNzM4NWUwODNjMjUzYTQ4ZTZhY2E5OTkyY2YwMDAwMDAwMTEyYTNkYmNlOTJhMTY5Y2UwNzczZDkxZkByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by5feFd3UF83bkVlV1c5aEw2MHItYUtRIn19LCJ1c2VySWQiOi0xfQ.nFWQHk0ok_v6FRb2ZYdpzeH3x3yyIK6zSu0QHQVR4z8>
Learner Help Center
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2xlYXJuZXIuY291cnNlcmEuaGVscC8_dXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uX3hXd1BfN25FZVdXOWhMNjByLWFLUSIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwNjM0OWIzM2JmM2E1MDFmZjAzNDM4ZmNmNzM4NWUwODNjMjUzYTQ4ZTZhY2E5OTkyY2YwMDAwMDAwMTEyYTNkYmNlOTJhMTY5Y2UwNzczZDkxZkByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by5feFd3UF83bkVlV1c5aEw2MHItYUtRIn19LCJ1c2VySWQiOi0xfQ.cfs7b6VvqShBeCF1TKFYx6SU9viTsBzJiD4l-YA16Ws> 
  | Please do not reply directly to this email
To no longer receive invitations from your friends on Coursera, 
Unsubscribe
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvYWNjb3VudC91bnN1YnNjcmliZS9SaUF0VHJCSHB2OXVST01LaTdXV2E1S2ltTzEzOXFJOUt0MjU3U2VEWVlxcndTZENkUDRKZTdkeHF2VXYxWnRBcHYxUHBVcDVkQktSR0NIMUdDWEVOUS42VEFfOEo2dWN6dDZNZzNibnhKRXdnLlcyRUo0M2QxVjRHUkJ0QnFpTXRjS1NBdXZNLVhCVnFlNHVaam5oaXBwcHhXTHlEcVJsY1BjQXRhc0ZCd19nMWNOWTh4c01pZU5NZUtodXpqa3Q0Yzd3LXhCZktZOHF5dXhyaFRTRE1ibkl0X1IweEhOMWJLUVRUaC1yNWlYRmRSZHdtS3gxTlg2RXRfUkZPT3NUd1pBOGwtUnpPX3FzamZTVzE2WDZ2VGU5UU5KaTBEVWEzWkMta2MwTWdPM19ka1QxTlVpVkFBZW5OcHpsSnktSm53OEV4bEJfeEZfSk1Bd0tMYmlsNnJjYXBDQ1BsNTRMcjlLbXV3M3ZxeWVIREdGMkY4REM5YzJQbjdxb2NqeFJYLTdxa3lacDIwSXp0RlJsMDRpb0xSbUpvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLl94V3dQXzduRWVXVzloTDYwci1hS1EiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDYzNDliMzNiZjNhNTAxZmYwMzQzOGZjZjczODVlMDgzYzI1M2E0OGU2YWNhOTk5MmNmMDAwMDAwMDExMmEzZGJjZTkyYTE2OWNlMDc3M2Q5MWZAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uX3hXd1BfN25FZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.oOwi1gsO85-S49L0B7Bd1kWOscUMWA0BvjIcu9ag0Vk>
Copyright © 2016, Coursera Inc. | 381 E. Evelyn Ave, Mountain View, CA 
94041 USA

**Comment by hhuhhu** [comment]
it's maily because you didn't link it.
I tried this and it worked.
ln -s /where/you/install/lib/*.so /usr/lib
sudo ldconfig

**Comment by mrjbq7** [comment]
Closing old issue.
