### ISSUE TITLE
Is it possible to add KDJ?

### ISSUE THREAD

**Issue by zhenyiy** [TA-Lib/ta-lib-python#99]
There is no KDJ in this package. Is it possible to add it? Thanks

**Comment by mrjbq7** [comment]
What is KDJ?

**Comment by zhenyiy** [comment]
It is a momentum indicator frequently used in Asia.
http://vb.letsfx.com/showthread.php/797-I-want-to-know-abou-KDJ-indicator

**Comment by mrjbq7** [comment]
```
%K = 100[(C – L5close)/(H5 – L5)]

C = the most recent closing price
L5 = the low of the five previous trading sessions
H5 = the highest price traded during the same 5 day period.

The formula for the more important %D line looks like this:
%D = 100 X (H3/L3)

Now calculate %J = 3 x D – 2 x K
```

**Comment by mrjbq7** [comment]
That looks easy to implement, I generally haven't been interested in adding indicators that aren't in the underlying ta-lib project (http://ta-lib.org)...

Seems like you could implement it yourself by doing something like this:

```python
import pandas as pd

def KDJ(C):
    L5 = pd.rolling_min(C, 5)
    H5 = pd.rolling_max(C, 5)
    K = 100 * (C - L5 / (H5 - L5) )
    D = 100 * H3 / L3
    J = (3 * D) - (2 * K)
    return K, D, J
```

**Comment by mrjbq7** [comment]
Note: I'm not sure if H3 and L3 are typos for H5 and L5, or if they mean the 3-day versions.

Also, not sure what L5close is in the pseudocode.

**Comment by zhenyiy** [comment]
It is a typo. Usually people use 9 days instead of 5 days or 3 days. I think I can implement it by myself. Thanks.

**Comment by 631068264** [comment]
@zhenyiy  you can use talib.STOCH to get K and D and then  J = (3 * D) - (2 * K)

**Comment by lfzCarlosC** [comment]
But the k d value is not correct as what you can see in other website with the same parameter 9,3,3

**Comment by mrjbq7** [comment]
Not correct how?

**Comment by lfzCarlosC** [comment]
This is one example of the result of what I have when using talib.STOCH:

2019-04-21 20:00:00  84.757888  87.737427  93.696504

This is what I got from tradingview:
<img width="662" alt="Screen Shot 2019-04-21 at 20 46 04" src="https://user-images.githubusercontent.com/17321822/56474204-cf660900-6476-11e9-9730-7f26d7cad14d.png">

**Comment by lfzCarlosC** [comment]
Also, even if I set parameter to 14,3,3 to compare only stoch value with what I saw in Trdaingview, it is also different.

**Comment by lfzCarlosC** [comment]
I opened an issue

**Comment by lfzCarlosC** [comment]
https://github.com/mrjbq7/ta-lib/issues/261

**Comment by lfzCarlosC** [comment]
It is more like a talib problem

**Comment by prashanth058** [comment]
```python
def KDJ(H, L, C):
    L5 = pd.rolling_min(L, 9)
    H5 = pd.rolling_max(H, 9)
    RSV = 100 * ((C - L5) / (H5 - L5)).values

    k0 = 50
    k_out = []
    for j in range(len(RSV)):
        if RSV[j] == RSV[j]: # check for nan
            k0 = 1/3 * RSV[j] + 2/3 * k0
            k_out.append(k0)
        else:
            k_out.append(np.nan)
    
    d0 = 50
    d_out = []
    for j in range(len(RSV)):
        if k_out[j] == k_out[j]:
            d0 =1/3 * k_out[j] + 2/3 * d0
            d_out.append(d0)
        else:
            d_out.append(np.nan)
    
    J = (3 * np.array(k_out)) - (2 * np.array(d_out))
    return pd.Series(J,  H.index)
```

The above might give KDJ values similar to the ones you see on trading view.

**Comment by sandy-mahajan** [comment]
> ```python
> def KDJ(H, L, C):
>     L5 = pd.rolling_min(L, 9)
>     H5 = pd.rolling_max(H, 9)
>     RSV = 100 * ((C - L5) / (H5 - L5)).values
> 
>     k0 = 50
>     k_out = []
>     for j in range(len(RSV)):
>         if RSV[j] == RSV[j]: # check for nan
>             k0 = 1/3 * RSV[j] + 2/3 * k0
>             k_out.append(k0)
>         else:
>             k_out.append(np.nan)
>     
>     d0 = 50
>     d_out = []
>     for j in range(len(RSV)):
>         if k_out[j] == k_out[j]:
>             d0 =1/3 * k_out[j] + 2/3 * d0
>             d_out.append(d0)
>         else:
>             d_out.append(np.nan)
>     
>     J = (3 * np.array(k_out)) - (2 * np.array(d_out))
>     return pd.Series(J,  H.index)
> ```
> 
> The above might give KDJ values similar to the ones you see on trading view.

Hi Prashant,

Does your code work for kdj calculation?

**Comment by mario4tier** [comment]
Thanks all, there is some good stuff here that I will need to review. AFAIK, the TA-Lib Stoch function is working as expected. I will need to revisit this discussion to understand the differences... may be in the way the inputs were fed to the functions?

====

Moving forward, all requests and further discussion for **new** functions should happen on the [New TA Functions Board]( https://github.com/orgs/TA-Lib/projects/1 )

A reference to this issue has been added to preserve this discussion. Thanks!
